Feature/bc 330 create user profile
yeezick/bootcampr pull request #10
Opened 2022-10-31 22:26 UTC by yeezick

Accomplishes [BC-330](https://bootcamper.atlassian.net/jira/software/c/projects/BC/boards/2?modal=detail&selectedIssue=BC-337):
- cleans up landing page to remove user and add login button to skip user sign in flow in development
- enables the user to visit and edit their profile
- renames all API snake_case properties to camelCase
- updates interfaces to match the new user model in [backend repo](www.google.com) 
- removes null acceptance from interfaces
- prepares the redux ui slice with object for auth status

2022-10-31 23:20 UTC, mendo94 requested changes
Please review the following and let us know your thoughts behind this pr.

2022-10-31 23:20 UTC, mendo94 commented on src/screens/UserProfile/EditProfile.tsx
> +          First Name
We didn't decide yet how we are going to layout our labels.

2022-10-31 23:20 UTC, mendo94 commented on src/screens/UserProfile/UserProfile.tsx
> +  if (!authUser) {
Is this temporary? If so, you could leave a comment to remove later.

2022-10-31 23:20 UTC, mendo94 commented on src/screens/UserProfile/EditProfile.tsx
> +    updateUserForm({ ...userForm, [name]: value });
Is this a supposed to be completed or needs to be finished in an upcoming ticket?

2022-11-01 22:48 UTC, yeezick commented on src/screens/UserProfile/EditProfile.tsx
> +    updateUserForm({ ...userForm, [name]: value });
sorry, i'm not sure what you're referring to specifically

2022-11-01 22:50 UTC, yeezick commented on src/screens/UserProfile/UserProfile.tsx
> +  if (!authUser) {
resolved this with a comment pointing to our jira ticket

2022-11-01 22:51 UTC, yeezick commented on src/screens/UserProfile/EditProfile.tsx
> +          First Name
We have not...

2022-11-02 00:23 UTC, mendo94 commented on src/screens/UserProfile/EditProfile.tsx
> +          First Name
Well this way will work

2022-11-02 00:28 UTC, mendo94 commented on src/screens/UserProfile/EditProfile.tsx
> +    updateUserForm({ ...userForm, [name]: value });
Oh! i mean the EditProfile component, was not sure if you were just setting this screen up and getting it ready for an upcoming EditProfile ticket or it is done. I was signed in, but I was not seeing the logged in user's information being rendered in the input values on the EditProfile screen - just the initial values in the useState.

2022-11-04 02:07 UTC, mendo94 approved these changes
After discussing I needed to reseed the data, it does render the correct information. Thank you AMAZING work you did here, need to merge this ASAP so i can follow your structure.

2022-11-05 19:08 UTC, merged