Feature/BC-617 email subscription flow
yeezick/bootcampr pull request #103
Opened 2023-11-12 02:35 UTC by gooliajulia

We decided to scrap this flow for Beta launch, but will eventually want to implement it. This work was done before this decision was made, and will still be valuable done the line once we implement the email subscription flow.

https://bootcamper.atlassian.net/browse/BC-617

This PR:
* Builds the foundational styling and functionality of the Email Preferences component
* Sets up path for a user's email preferences screen
* Sets up 2 api utils for fetching preference options and current user preferences

2023-11-12 23:27 UTC, yeezick commented
implementation looks fine but i'm curious why we need to store email pref types in the backend and make a call to fetch them?

2023-11-13 16:07 UTC, gooliajulia commented
@yeezick The idea was to have one source of truth so we only have to change the information in one place. Not necessarily beneficial if this info only needs to be accessed by one place, but eventually might be used my more places in backend and frontend.

I'm okay with keeping it or nixing it and just storing on FE

2023-11-20 22:13 UTC, yeezick commented on src/screens/EmailPreferences/EmailPreferences.tsx
> +            handler={() => console.log('save preferences')}
console.log

2023-11-20 22:14 UTC, yeezick commented on src/screens/EmailPreferences/EmailPreferences.tsx
> +  }
since you're passing option as the name you can destructure it from `e`, removing the need to pass a second argument and the anon function in the checkbox

2024-01-03 23:24 UTC, yeezick requested changes
marking as requested changes

2024-02-22 01:29 UTC, yeezick commented
closing this PR but we know it exists if we need to revive it

2024-02-22 01:29 UTC, closed without merging