BC-580 | Align Reset Password and Change Password flow with HiFi
yeezick/bootcampr pull request #104
Opened 2023-11-12 04:05 UTC by jasonmar08

[BC-580](https://bootcamper.atlassian.net/browse/BC-580?atlOrigin=eyJpIjoiOWFhY2JiNTI4NzMxNDhiM2E0ZDdhNjIxMDlhOGI3NjYiLCJwIjoiaiJ9)

2023-11-12 04:15 UTC, jasonmar08 commented on src/screens/Auth/Settings/DeleteAccountModal.tsx
> +// }
I left this to compare the user of the reusable SettingsModal versus creating a separate modal for each use case.

2023-11-12 04:15 UTC, jasonmar08 commented on src/screens/Auth/Settings/DeleteAccountModal.tsx
> +      {/* <Modal
Here too

2023-11-12 04:15 UTC, jasonmar08 commented on src/screens/Auth/Settings/Settings.scss
> +// }
Styling from the replaced modal in Delete Account

2023-11-12 23:29 UTC, yeezick commented on src/components/Inputs/Passwords.tsx
> +
this looks like the same function on L93

2023-11-12 23:30 UTC, yeezick commented on src/components/Inputs/Passwords.tsx
> -          />
does replacing this with mui icons mean we can delete those png's?

2023-11-12 23:34 UTC, yeezick commented on src/components/Inputs/Passwords.tsx
> +        <RxCross2 className='criteria-cross' size={14} />
this is better as a ternary as it would need to be one or the other imo, not required to change.

2023-11-12 23:35 UTC, jasonmar08 commented on src/components/Inputs/Passwords.tsx
> -          />
Yes, instead of the png, I'm using a React-Icon

2023-11-12 23:36 UTC, yeezick commented on src/components/Inputs/Passwords.tsx
> +  disableErrorState = () => {},
does disableErrorState need to be initialized as anon function?

2023-11-12 23:37 UTC, yeezick commented on src/components/Inputs/Passwords.tsx
> +              }}
turn this into a handler

2023-11-12 23:39 UTC, jasonmar08 commented on src/components/Inputs/Passwords.tsx
> +
Yes, it's similar. I meant to make a handler function for it.

One is for the "New password" input field label, and the other is for the "Re-enter new password" input field label for the different screens (Sign Up, Change Password, Password Reset). They appear differently in Figma for the same input. Not sure if this was intentional.

2023-11-12 23:46 UTC, jasonmar08 commented on src/components/Inputs/Passwords.tsx
> +  disableErrorState = () => {},
Although I made it an optional prop in the interface, it was still giving me an error because I needed to add a default value for it.

2023-11-12 23:49 UTC, yeezick requested changes
good work -- have a few items i need to review personally. will try to get back to this by wednesday. let's connect before then to discuss the generic modal and success screens.

2023-11-12 23:49 UTC, yeezick commented on src/components/SettingsModal/SettingsModal.tsx
i have to review this function to see if we can simplify the amount of props being passed into this
at first glance, i'm thinking we create a base modal component that is used in unique modal components
this way we can make those variants in charge of their unique settings vs having to consider & fill in the props before every use

2023-11-12 23:49 UTC, yeezick commented on src/screens/AccountSettings/components/ForgotPasswordLink.tsx
> +      />
let's discuss my suggestion above over a call

2023-11-12 23:49 UTC, yeezick commented on src/screens/Auth/Settings/Password.tsx
> +
curious about the need to use theme here if u can explain it to me -- i don't understand its use cases v well

2023-11-12 23:49 UTC, yeezick commented on src/screens/SuccessScreen/SuccessScreen.tsx
i see what you've done here... curious about this one too. marking it for myself to review.

2023-11-15 06:32 UTC, jasonmar08 commented on src/screens/Auth/Settings/Password.tsx
> +
This assigns the background color to the base layer of an MUI Button to leverage the layering system of MUI Buttons, as opposed to setting the hover, active, and disabled states separately in CSS. This could be wrapped around the entire app in index.ts once we decide on the global colors for buttons and this would be removed from here.

2023-11-20 22:11 UTC, yeezick commented on src/screens/Auth/Settings/DeleteAccountModal.tsx
> +// }
this can be deleted now

2023-11-20 22:12 UTC, yeezick requested changes
just need to remove dead comments

2023-11-21 00:34 UTC, yeezick approved these changes

2023-11-21 00:34 UTC, merged