Feature/bc 488 show invitee availability
yeezick/bootcampr pull request #108
Opened 2023-12-08 16:06 UTC by yeezick

Accomplishes [BC-488: Add availability to meeting modal](https://bootcamper.atlassian.net/browse/BC-488?atlOrigin=eyJpIjoiZDRkODIzMTE3NzAwNDMwYzliMDQyYWYzYmMwMjVlMTEiLCJwIjoiaiJ9)
* Adds availability each member checkbox 
* Separates SelectAttendees components and stylesheets into their own files 
* Creates a directory for stylesheets

2023-12-19 02:11 UTC, HectorIlarraza requested changes

2023-12-19 02:11 UTC, HectorIlarraza commented on src/components/Calendar/MeetingModal/SelectAttendees.tsx
> +            {projectMembers.map(currMember => (
Should a key be added for better optimization?

2023-12-19 02:11 UTC, HectorIlarraza commented on src/interfaces/UserInterface.ts
> +//TODO: Removed string from sun interface....
Seems like this can be removed now with type string gone no?

2023-12-20 01:12 UTC, yeezick commented on src/components/Calendar/MeetingModal/SelectAttendees.tsx
> +            {projectMembers.map(currMember => (
a key is provided in the member checkbox component itself

2023-12-20 01:15 UTC, yeezick commented on src/interfaces/UserInterface.ts
> +//TODO: Removed string from sun interface....
yes actually

2023-12-20 22:10 UTC, HectorIlarraza approved these changes

2023-12-20 23:39 UTC, merged