Feature/bc 260 user dashboard
yeezick/bootcampr pull request #11
Opened 2022-11-01 17:34 UTC by Bestnogm1

added the dashboard and created the dashboard folder and file added the routes to see the detail of the project

2022-11-28 23:22 UTC, zendrias commented on src/App.tsx
> +import Dashboard from './screens/Dashboard/Dashboard';
Keep imports consistent with curly braces

2022-12-01 00:10 UTC, Bestnogm1 reviewed
fixed import

2022-12-02 16:44 UTC, yeezick requested changes
@zendrias please be more thorough in your reviews. 
compare with other files in the codebase to identify how to keep our style guides and best practices consistent. 
@Bestnogm1 good work, just needs some refinement & merge with dev.

2022-12-02 16:44 UTC, yeezick commented on src/utilities/types/UserInterface.ts
> +  memberOfProjects?: ProjectInterface[] | null;
since `memberOfProjects` already has a `?` we don't need to add null. The api will just not return it.

2022-12-02 16:44 UTC, yeezick commented on src/utilities/Interface/ProjectInterface.ts
> +export interface ProjectInterface {
we already have a ProjectInterface in `types/` ?

2022-12-02 16:44 UTC, yeezick commented on src/screens/Dashboard/Dashboard.tsx
> +    <>
Also, simplify this component by adding an if statement before the render instead of conditionally rendering the return 
if (!user) return <p> no project yet </p>

return (<rest of file since user exists/>)

2022-12-20 00:24 UTC, closed without merging