Feature/BC- 643-hifi-landing-page
yeezick/bootcampr pull request #113
Opened 2024-01-01 01:41 UTC by JustFelix-Dev

- Created landing page to match hi-fi design
- Componentized landing page section for better readability.
-  Created a "Contact Us" section at the bottom of the page to facilitate user inquiries.
-Implemented fields for Name, Email Address, and Message in the "Contact Us" section.
-Ensured the Submit button is always active, allowing users to easily submit their inquiries.
-Implemented error states with clear messages to guide users when attempting to submit without providing all necessary information.

Jira Ticket : https://bootcamper.atlassian.net/browse/BC-643

2024-01-02 21:06 UTC, gooliajulia requested changes
AWESOME attention to detail 👏  - this screen looks great.
Some minor additional comments:
* The three images "Build a product" "Gain experience" "Join a team" are aligning to the left on larger window widths (see attached screenshot) - please center these
* It looks like the font inside the Message input box in the Contact Us form is different than the figma?

Other than that everything looks great! Let me know when you're able to address all comments and I'll take another look
![Screenshot 2024-01-02 at 2 03 32 PM](https://github.com/yeezick/bootcampr/assets/87200663/da7907a3-7850-4d75-8379-8855c249e2f1)

2024-01-02 21:06 UTC, gooliajulia commented on src/screens/Landing/components/Hero/Hero.scss
> +.hero-container{
alphabetize

2024-01-03 23:02 UTC, gooliajulia approved these changes
Awesome, thanks for making these changes. Looks good to me!

2024-01-03 23:18 UTC, yeezick commented on src/screens/Landing/components/HowItWorks/HowItWorks.tsx
> +          </span>
this can be converted into a reusable component as the same html is repeated 3x

2024-01-03 23:19 UTC, yeezick commented on src/screens/Landing/components/IsThisForYou/IsThisForYou.tsx
> +          </span>
same comment as above, component can be reused again here

2024-01-03 23:20 UTC, yeezick commented on src/screens/Landing/components/WorkFlow/WorkFlow.tsx
> +      </div>
these elements all share the same html, can be turned into a reusable componet

2024-01-03 23:20 UTC, yeezick commented on src/screens/Landing/components/YourProjectPortal/YourProjectPortal.tsx
> +        </div>
these seemlike they use the same thml, can be converted into a reusable component

2024-01-03 23:21 UTC, yeezick requested changes
a lot of opportunity to reduce html pollution by creating reusable components

2024-01-07 08:05 UTC, yeezick commented on src/layout/Nav/Nav.tsx
> +          </Link> */}
looks like dead code here

2024-01-07 08:07 UTC, yeezick commented on src/screens/Landing/components/ContactForm/ContactForm.scss
> +      align-items: flex-start;
i won't hold the pr back over this but best practice is to have a space between the selector and the curlies `.contact-wrapper {}` 
and to have a line break between selectors
```
.contact-wrapper {}

.contact-header {}
```

2024-01-07 08:08 UTC, yeezick commented on src/screens/Landing/components/ContactForm/ContactForm.tsx
> +    // Update word count
no need for most of these comments, the code speaks for itself

2024-01-07 08:09 UTC, yeezick commented on src/screens/Landing/components/ContactForm/ContactForm.tsx
> +              )}
we should replace these with MUI text inputs if possible. the MUI components should even have properties to help with displaying error messages

2024-01-07 08:09 UTC, yeezick commented on src/screens/Landing/components/ContactForm/ContactForm.tsx
> +          <button className='contact-button'>Submit</button>
this should be an MUI button as well

2024-01-07 08:09 UTC, yeezick commented on src/screens/Landing/components/ContactForm/ContactForm.tsx
> +                      color: hasErrors && formErrors.message ? '#B71C1C' : '',
i see this conditional repeated a lot, might as well save it to a variable and reuse it.

2024-01-07 08:14 UTC, yeezick commented on src/screens/Landing/components/WorkFlow/WorkFlowItem.tsx
> +}
* move types/interfaces to the interfaces directory
* change variables "text1" and "text2" to more semantic variables. they're not semantic and don't describe what they're used for. judging from the figma, `text1` looks like a subtitle and `text2` looks like the actual text

2024-01-07 08:14 UTC, yeezick commented on src/screens/Landing/components/YourProjectPortal/DetailsContent.tsx
> +type DetailsContentProps = {
move types to the interfaces directory

2024-01-07 08:14 UTC, yeezick commented on src/screens/Landing/components/YourProjectPortal/YourProjectPortal.scss
add spaces between selectors and their curly brackets

2024-01-07 08:15 UTC, yeezick commented on src/screens/Landing/components/YourProjectPortal/YourProjectPortal.tsx
> +
extra whitespace here

2024-01-07 08:17 UTC, yeezick commented on src/screens/Landing/components/YourProjectPortal/YourProjectPortal.tsx
> +import projectImage5 from 'assets/Images/project-image-5.png'
these image variables & their files should be renamed to something semantic, for example: `projectImage1` could be something like `laptop-project-details.png`

2024-01-07 08:17 UTC, yeezick commented
sorry i noticed more things on the second review, let me know if you have any questions!

2024-01-08 09:27 UTC, JustFelix-Dev commented on src/screens/Landing/components/ContactForm/ContactForm.tsx
> +              )}
Yeah, you are right MUI has an helperText and error prop for handling errors but my concern is with the floating label style MUI uses for it's input field.. It wouldn't match the hifi design..

2024-01-08 18:14 UTC, yeezick commented on src/interfaces/LandingPageInterfaces.ts
> +}
alphabetize props

2024-01-09 07:46 UTC, JustFelix-Dev commented on src/screens/Landing/components/ContactForm/ContactForm.tsx
> +          <button className='contact-button'>Submit</button>
Done!

2024-01-09 08:07 UTC, JustFelix-Dev commented on src/screens/Landing/components/ContactForm/ContactForm.tsx
> +                      color: hasErrors && formErrors.message ? '#B71C1C' : '',
Done!

2024-01-10 04:08 UTC, yeezick approved these changes
looks good to go!

2024-01-10 07:34 UTC, merged