Feature/bc 620 user not matched with a team
yeezick/bootcampr pull request #117
Opened 2024-01-03 04:35 UTC by HectorIlarraza

### Feature: User Not Matched With a Team

This pull request involves implementing error handling for users who have not yet been added to any team within the Bootcampr platform. Additionally, it includes creating a designated screen for unassigned users to provide guidance and information.

### Changes Made:

1. Project Portal Access for Unassigned Users:

- Implemented error handling for users who have completed onboarding but have not been added to any team or when the team composition (3 SWDs and 2 UXDs) is incomplete.
- Enabled access to the project details section within the project portal for these users, allowing them to view project information.

2. Limited Access for Unassigned Users:

- Users without team assignments can access the team page but are restricted from accessing the calendar and task management sections.
- Inactivated the submit button in the side menu for users not yet assigned to a team.

3. Unassigned User Page Creation:

- Implemented an "Unassigned User" screen specifically for users not added to any team.
- Implemented a message within the Teams section informing users that Bootcampr is in the process of matching them to a team.

### Review Notes:

Implemented error-handling mechanisms for users not currently matched with a team or when the team composition requirements are incomplete. These users can access the project details section but cannot access other functionalities like calendar and task management.

Additionally, an "Unassigned User" screen has been successfully developed, displaying a message within the Teams section to inform users about the ongoing process of team assignment.

### Deployment Notes:

No specific deployment requirements or changes are necessary for this feature implementation. The updates will be included in the next deployment cycle.

**_Please review the changes and provide feedback as necessary. Thank you!_**

2024-01-03 19:43 UTC, GeoSauer requested changes
Great work! I only noticed a couple small edits, and had one question due to my current unfamiliarity with the repos.

2024-01-03 19:43 UTC, GeoSauer commented on src/screens/Project/ProjectDetails/NotInTeamProjectAlert.scss
> +      font-size: 400;
Is this one supposed to be `font-weight: 400`?

2024-01-03 19:43 UTC, GeoSauer commented on src/screens/Project/ProjectDetails/NotInTeamProjectAlert.tsx
> +        const response = await getProjectByUser(projectId)
New to the product and what all the API routes do so bare with me, but should this be `getOneProject(projectId)` or `getProjectByUser(userId)`?

2024-01-03 19:43 UTC, GeoSauer commented on src/layout/SideMenu/SideMenu.scss
> +    border: none;
I think these two need to be swapped for alphabetical-ness?

2024-01-03 23:01 UTC, yeezick commented on src/layout/SideMenu/SideMenu.tsx
> +      <SideMenuLinks notInTeam={notInTeam} />
no need to useAppSelector in this component if we are only drilling it down into sidemenulinks, can just call the selector within sidemenulinks

2024-01-03 23:02 UTC, yeezick commented on src/layout/SideMenu/SideMenu.tsx
> +      <SideMenuLinks notInTeam={notInTeam} />
ah i see, that we are using it for the button, regardless, dont make sidemenulinks dependent on the prop being passed; just call the selector again within that component

2024-01-03 23:02 UTC, yeezick commented on src/layout/SideMenu/SideMenu.tsx
> +const MenuLink = ({ linkDetails, notInTeam }) => {
same as above comment

2024-01-03 23:04 UTC, yeezick commented on src/screens/Project/ProjectDetails/NotInTeamProjectAlert.tsx
> +  const { projectId } = useParams<{ projectId: string }>()
convert { projectId: string } into a named type

2024-01-03 23:04 UTC, yeezick commented on src/screens/Project/ProjectDetails/NotInTeamProjectAlert.tsx
> +        const response = await getProjectByUser(projectId)
why do we need to make an api call to check if project exists? 
can't we just check if the auth user has a project id within redux?

2024-01-03 23:05 UTC, yeezick commented on src/screens/Project/ProjectDetails/NotInTeamProjectAlert.tsx
> +            <div dangerouslySetInnerHTML={{ __html: alertBanner.text }} />
dangerous, is this the only way to make this work?

2024-01-03 23:06 UTC, yeezick commented on src/screens/Project/ProjectDetails/NotInTeamProjectAlert.tsx
> +      ) : null}
no need for ternary if falsy condition will return null, just use &&

2024-01-04 12:30 UTC, HectorIlarraza commented on src/screens/Project/ProjectDetails/NotInTeamProjectAlert.tsx
> +        const response = await getProjectByUser(projectId)
Well, I am calling the API to trigger the response message from the backend (see backend PR ticket) that was already set up in that way to display the alert for it in the frontend. I could use the redux approach but does that mean I need to create the message from the FE instead? This would help avoid using the "dangerouslySetInnerHTML" I had to use to get it to work with the backend message.

2024-01-04 12:40 UTC, HectorIlarraza commented on src/screens/Project/ProjectDetails/NotInTeamProjectAlert.tsx
> +            <div dangerouslySetInnerHTML={{ __html: alertBanner.text }} />
Its because the message is coming from the backend and how long the message is with the line breaks needed to space it out to match Figma is the only way i could get it to display correctly. But if i use the redux method discussed in the earlier comment above i can avoid this method. I will bring up in today's meeting.

2024-01-04 17:02 UTC, HectorIlarraza commented on src/utils/redux/slices/projectSlice.ts
> +
I was going by at least having a team member or being a part of a team when i created this but if the projectID is good enough then I'll make that change to reflect that but that means i would also need to do that for the BE and FE conditional as well which looks for the member count to trigger the alert. Depending on removing the message from the BE have the FE handle it like i mentioned in the above comments.

2024-01-07 08:21 UTC, yeezick commented on src/screens/Project/ProjectDetails/NotInTeamProjectAlert.tsx
> +        const response = await getProjectByUser(projectId)
If I'm understanding this correctly -- yes, let's avoid making an API call just for an error message.

2024-01-07 08:22 UTC, yeezick commented on src/utils/redux/slices/projectSlice.ts
> +
yes, let's rely solely on the projectId

2024-01-08 18:12 UTC, yeezick approved these changes

2024-01-10 04:19 UTC, merged