Feature/bc 651 finalize kanban hifi
yeezick/bootcampr pull request #122
Opened 2024-01-07 21:16 UTC by yeezick

WIP

2024-01-08 17:59 UTC, HectorIlarraza requested changes
Love Hi-Fi tickets because on how much you can optimize and refactor the ole Lo-Fi ones and you absolutely crushed that. Only have some questions and fixes needed so we merge this bad boi, Great work!

2024-01-08 17:59 UTC, HectorIlarraza commented on src/components/Kanban/TaskBoard/styles/BoardColumnStyles.scss
> +  height: calc(100% - 26px); // 26px by eyesight, can be better, parent div extends into footer?
Is it breaching the margin from the footer or overlapping the footer? Can you paste a screenshot since github now allows you to do this in comments now? I might be able to solve this if i can see how it looks.

2024-01-08 17:59 UTC, HectorIlarraza commented on src/layout/Layout.scss
> +    max-width: calc(100% - 272px); // 272px coming from width of sidemenu
ABC order

2024-01-08 17:59 UTC, HectorIlarraza commented on src/layout/Layout.scss
> +    max-width: calc(100% - 272px); // 272px coming from width of sidemenu
and comment removal

2024-01-08 17:59 UTC, HectorIlarraza commented on src/layout/Layout.tsx
> +          className={
Let's create a var that contains this boolean logic for readability and cleanliness.

2024-01-08 17:59 UTC, HectorIlarraza commented on src/screens/Project/TaskManagment.tsx
> +  if (project) {
Hmmmm 🤔 should we create another filler screen similar to what Jason created for UnassignedProject.tsk or since my ticket for BC-620 which you are reviewing is handling this kind of since if a user doesn't have a projectId they can't even click on the Task Management button on the sideMenu component. What do you think?

2024-01-29 23:29 UTC, yeezick commented on src/screens/Project/ProjectDetails/ProjectDetails.scss
>    .pd-header {
safe to delete

2024-01-30 00:19 UTC, yeezick commented on src/layout/Layout.scss
> +    max-width: calc(100% - 272px); // 272px coming from width of sidemenu
comment is intentional to indicate where the value is coming from

2024-01-30 21:51 UTC, HectorIlarraza reviewed
Honestly Eric you have taken MUI SME in to a new level with this massive overhaul and additions you did on this ticket. This is probably worth at least 3-4 tickets worth of work, Great Job man. Learned a lot! Just have a few questions and quick corrections.

2024-01-30 21:51 UTC, HectorIlarraza commented on src/components/TeamAvatar/TeamAvatar.tsx
> +            src='/default_profile.png'
Wait is this some type of guard clause if there is no user at all we give a default_profile.png like from Faker user DB? Wouldn't the else conditional take care of the default profile image using the initials var defaultImageURL?

2024-01-30 21:51 UTC, HectorIlarraza commented on src/screens/Project/TaskManagement/TaskBoard/BoardColumns/TicketTab.tsx
> +      {provided => (
Wait where is "provided" coming from? Did you create a function inside the JSX 😮 !?

2024-01-30 21:51 UTC, HectorIlarraza commented on src/screens/Project/TaskManagement/TicketDialog/Fields/TicketCreator.tsx
> +  const [creator, setCreator] = useState({
Couldn't we create an instance or types and call it here?

2024-01-30 21:51 UTC, HectorIlarraza commented on src/utils/functions/utilityFunctions.js
> +
I believe a short description would help this util function since its kinda of literal and generalistic which i guess makes sense on why this was an approach to take 🤔 , what do you think?

2024-01-31 21:01 UTC, yeezick commented on src/components/Buttons/PrimaryButton.tsx
> +    textTransform: 'none', // textTransform can't be added to secondaryButtonSx or it throws a type error?
this comment is better inline instead of another document so that devs can see the the impact here directly instead of needing to refer to another document (which they probably wouldnt do)

2024-01-31 23:07 UTC, yeezick commented on src/components/TeamAvatar/TeamAvatar.tsx
> +            src='/default_profile.png'
this is using the default avatar for when the "unassigned" user is selected in the assignees dropdown of ticket modal

2024-01-31 23:10 UTC, yeezick commented on src/screens/Project/TaskManagement/TicketDialog/Fields/TicketCreator.tsx
> +  const [creator, setCreator] = useState({
unsure what you're asking for here

2024-01-31 23:39 UTC, yeezick commented on src/screens/Project/TaskManagement/TicketDialog/Fields/TicketCreator.tsx
> +  const [creator, setCreator] = useState({
this is nbd, the initial state needs to be defined anyway

2024-01-31 23:52 UTC, HectorIlarraza approved these changes
🧼

2024-02-01 00:06 UTC, merged