BC-638/HiFi Onboarding Flow
yeezick/bootcampr pull request #126
Opened 2024-01-16 15:46 UTC by gooliajulia

This PR:
* Matches complete Onboarding flow styling to Figma designs
* Replaces hardcoded buttons with BC component buttons
* Expands BC component buttons to allow for dynamic use: disabled, custom style tweaks (only intended for minor stylistic changes, styling will always default to the standard design system button)
* Cleans up data storage on Onboarding flow so user info is always stored and auto populated
* Fixes timezone input bugs
* Creates reusable BC Tool Tip component
* Ensures a user will be directed to the screen of Onboarding flow where they left off
* Adds error states and disable "next" button logic to entire flow
* Adds a real Google Forms survey for user's to click to and fill out
* Matches Paginator logic to Figma (cannot navigate manually and only highlights current page, not all completed) and adjusts Paginator component accordingly

2024-01-17 19:42 UTC, yeezick commented on src/components/Availability/Availability.scss
> +            //
beep

2024-01-17 19:58 UTC, yeezick requested changes
linting changes, logic looks good, some suggestions to follow up on later but not hard blocks to this pr

2024-01-17 19:58 UTC, yeezick commented on src/components/Availability/subcomponents/TimeslotInput.tsx
> +            {/* TODO: make a reusable component for these? */}
should this be followed up on?

2024-01-17 19:58 UTC, yeezick commented on src/components/Availability/subcomponents/TimeslotInput.tsx
wonder if it would be worth to break into multiple files, not a hard block though

2024-01-17 19:58 UTC, yeezick commented on src/screens/Onboarding/Onboarding.scss
ideally this stylesheet should be componentized, not a hard block, can be followed up

2024-01-17 19:58 UTC, yeezick commented on src/screens/Onboarding/Onboarding.tsx
> +    )
do we need the checks for .length? 
`''` is treated as falsy in conditionals

2024-01-17 19:58 UTC, yeezick commented on src/screens/Onboarding/SetUpProfile.tsx
> +      links.linkedinUrl.length > 0
do we need to check for .lengths? 
`''` is treated as falsy in conditionals

2024-01-17 19:58 UTC, yeezick commented on src/screens/Onboarding/WhatsNext.tsx
> +            </span>{' '}
linter dropped some `{' '}`

2024-01-17 23:25 UTC, gooliajulia commented on src/components/Availability/subcomponents/TimeslotInput.tsx
> +            {/* TODO: make a reusable component for these? */}
feels very much like a nice to have because the code repeats in this file - but since the component wouldn't be used outside of this case I think we can save the effort

2024-01-17 23:30 UTC, gooliajulia commented on src/screens/Onboarding/Onboarding.tsx
> +    )
Ahh good call. I must have been thinking of arrays. will update

2024-01-19 16:28 UTC, gooliajulia commented on src/components/Availability/subcomponents/TimeslotInput.tsx
Just pulled CopyTimesModal into its own file

2024-01-22 14:55 UTC, gooliajulia commented on src/screens/Onboarding/Onboarding.scss
Refactored

2024-01-25 00:09 UTC, yeezick approved these changes

2024-01-25 00:16 UTC, merged