Feature/bc 649 hifi calendar
yeezick/bootcampr pull request #128
Opened 2024-01-16 19:54 UTC by jordanje

- styled calendar page header, tabs, buttons, meeting modals, and popups to match figma design
- edited editable meeting modal and display meeting modal to handle all functionality 
- created cancel meeting modal, don't save modal, and alert notification when meeting created
- started on delete meeting functionality (not finished, redux/node code needs work)
- started on calendar styling (not finished)

2024-01-17 22:12 UTC, yeezick requested changes

2024-01-17 22:12 UTC, yeezick commented on src/screens/Calendar/MeetingModal/EditableMeetingModal/MeetingModalHeaderIcons.tsx
> +  // const handleBackToDisplay = () => dispatch(setModalDisplayStatus('display'))
commented out code, or is this for the delete functionality?

2024-01-17 22:12 UTC, yeezick commented on src/screens/Calendar/MeetingModal/EditableMeetingModal/MemberCheckbox.tsx
> +    const determineUserAvailability = (
let's move this function to a util file to keep the useEffect clean and the component easier to read
when functions get too large we can move them to utils even though they only get used once to keep their implementation files more concise, legible

2024-01-17 22:12 UTC, yeezick commented on src/screens/Calendar/MeetingModal/styles/Datefields.scss
>  }
these comments also for the continued work?

2024-01-17 22:12 UTC, yeezick commented on src/screens/Calendar/MeetingModal/styles/MemberCheckbox.scss
> +
noticing a lot of extra whitespaces throughout your SCSS, eventually we'll want to look at an SCSS formatter but for now let's try to avoid them

2024-01-17 22:12 UTC, yeezick commented on src/utils/redux/slices/calendarSlice.ts
> +      delete state.eventMap[eventId]
so this would be 
`state.convertedEvents = state.convertedEvents.filter(event => event.eventId !== eventId)`
 assuming that the issue here was the assignment and 
```
const { eventId, ...filteredEventMap } = state.eventMap
state.eventMap = filteredEventMap
```
assuming it was the delete that wasn't working 

if these 2 suggestions actually fix the issue then we'll both have learned that reducers need explicit assignments

2024-01-17 22:13 UTC, yeezick commented on src/screens/Calendar/CalendarHeader.tsx
> +        </OrangeButton>
nevermind, we can come back to this when implement the primary button, don't want this to hold you back

2024-01-17 22:13 UTC, yeezick commented on src/screens/Calendar/MeetingModal/DisplayMeetingModal/DisplayAttendees.tsx
> +
refer to below comment about SCSS

2024-01-17 22:14 UTC, yeezick commented on src/screens/Calendar/CalendarView.scss
> +}
refer to comment about whitespace below

2024-01-17 22:15 UTC, yeezick commented
really good job! love the componentization!! 
few suggestions on cleaning up code but the implementation looks good to me!

2024-01-17 22:46 UTC, yeezick requested changes
comments above

2024-01-17 23:59 UTC, jordanje commented on src/screens/Calendar/MeetingModal/DisplayMeetingModal/DisplayModalHeaderIcons.tsx
> +  eventId,
Whoops forgot this one. Will fix

2024-01-18 00:00 UTC, jordanje commented on src/utils/redux/slices/calendarSlice.ts
> +      delete state.eventMap[eventId]
I ended up taking out this code for now. I want to have some extra time to change it before submitting it actually

2024-01-18 18:37 UTC, yeezick approved these changes

2024-01-18 18:39 UTC, merged