Bc 341 sidebar menu
yeezick/bootcampr pull request #13
Opened 2022-11-07 19:53 UTC by mendo94

Please see bc-341 Jira ticket for a visual on the sidebar component.

2022-11-16 00:31 UTC, HectorIlarraza requested changes
Overall a great PR Rina this is my first official review of one so I hope I clarified enough on possible suggestions, if not please feel free to hit me up so we can do a walkthrough of it.

2022-11-17 01:42 UTC, mendo94 commented on src/layout/Nav/Nav.tsx
>    const authUser = useSelector(selectAuthUser);
changed authUser._id and used UseApp selector instead.

2022-11-17 01:42 UTC, mendo94 commented on src/index.tsx
> +  <Router>
Yes I should have added the router to the index file to begin with, but here we are changing it now

2022-11-17 01:43 UTC, mendo94 commented on src/layout/Nav/Nav.tsx
> +        {authUser._id !== '' ? (
changed authUser.id to userId

2022-11-17 01:44 UTC, mendo94 commented on src/layout/Sidebar/Sidebar.tsx
> +            {authUser.firstName ? authUser.firstName : 'Wiggly'} {authUser.lastName ? authUser.lastName : 'Jones'}
then don't be that guy.... changed authUser.first and last to just firstName and lastName.

2022-11-17 02:04 UTC, mendo94 commented on src/layout/Nav/Nav.tsx
>  import { selectAuthUser } from '../../utilities/redux/slices/users/userSlice';
imported the hooks

2022-11-18 01:19 UTC, mendo94 commented on src/layout/Sidebar/Sidebar.tsx
> +    <div className={props.isOpen ? 'sidebar-container active' : 'hide-sidebar'}>
Changed isOpen to visibleSidebar for more clarity

2022-11-18 01:22 UTC, mendo94 commented on src/layout/Sidebar/Sidebar.tsx
> +import { selectAuthUser } from '../../utilities/redux/slices/users/userSlice';
replaced to the hooks

2022-11-18 01:22 UTC, mendo94 commented on src/layout/Nav/Nav.tsx
> +interface SidebarProps {
imported the sidebar from the userslice and used dispatch to handle the function.

2022-11-18 01:28 UTC, mendo94 commented
Resolved all outstanding errors and ready for second review

2022-11-18 07:29 UTC, HectorIlarraza approved these changes
Excellent Rina! All changes are resolved and approved for the next steps!

2022-11-18 12:37 UTC, merged