brand new commit for my chat hifi
yeezick/bootcampr pull request #139
Opened 2024-02-02 01:44 UTC by ozggnr

- Refactored and removed unused and cleaned up components
- matched styling figma hifi
- created useSocketEvent hook and added sockets to listen changes in related pages - when user is in the room (active) and when they are not in the room (inactive)
- calculated and displayed unread message count on navigation when they open the page
- created generic badge component to use on message icon and chat list
- made user thumbnail more generic to use in different pages
- expand message text box in chat room
- added invite members page with updated users list and send email notification
- removed projectByUser, which was removed from backend before
- created generic component for empty chat pages when there are no messages

[HIFI/BC-657-chat](https://bootcamper.atlassian.net/browse/BC-657)

2024-02-02 02:07 UTC, yeezick commented on src/components/ChatDialog/ChatDialogMain/ChatDialogMain.scss
pls alphabetize stylesheets so css properties are easier to find
use this comment as a general comment for all scss files. 

also, add a line break between each selector

2024-02-02 02:34 UTC, yeezick requested changes
one word: impressive

very nice pr ozge. most comments are regarding linting or best practice, no real qualms with any of the logic other than what i have called out 

for comments with "use as general comment" please apply those comments to the whole PR

2024-02-02 02:34 UTC, yeezick commented on src/components/ChatDialog/ChatDialogMain/ChatDialogMain.scss
pls alphabetize stylesheets so css properties are easier to find
use this comment as a general comment for all scss files.

also, add a line break between each selector

2024-02-02 02:34 UTC, yeezick commented on src/components/ChatDialog/ChatDialogMain/ChatDialogMain.tsx
love this file's componentization

2024-02-02 02:34 UTC, yeezick commented on src/components/ChatDialog/ChatDialogMain/ChatHeader.tsx
> +  )
add line breaks between functions

2024-02-02 02:34 UTC, yeezick commented on src/components/ChatDialog/ChatDialogMain/ChatHeader.tsx
> +  )
use as general comment for all functions

2024-02-02 02:34 UTC, yeezick commented on src/components/ChatDialog/ChatDialogMain/ChatHeader.tsx
> +
delete white space

2024-02-02 02:34 UTC, yeezick commented on src/components/ChatDialog/ChatDialogMain/ChatHeader.tsx
> +
use as general comment

2024-02-02 02:34 UTC, yeezick commented on src/components/ChatDialog/ChatDialogMain/ChatHeader.tsx
> +          className='group-link'
lets name this function above so it is easier to debug 
anon functions waste memory

2024-02-02 02:34 UTC, yeezick commented on src/components/ChatDialog/ChatDialogMain/ChatHeader.tsx
> +          className='group-link'
use as general comment

2024-02-02 02:34 UTC, yeezick commented on src/components/ChatDialog/ChatMemberProfile/ChatMemberProfile.tsx
does this file need a follow up?

2024-02-02 02:34 UTC, yeezick commented on src/components/ChatDialog/ChatRoom/ChatRoom.tsx
> +    }
remove extra comments, only one worth keeping is the one on line 28

2024-02-02 02:34 UTC, yeezick commented on src/components/ChatDialog/ChatRoom/ChatRoom.tsx
> +    // Send message with 'Enter' key, Does not send with 'Enter' + 'Shift'
i actually think we should prefer to send with shift enter over just shift.. we can bring up with UX if needed

2024-02-02 02:34 UTC, yeezick commented on src/components/ChatDialog/UserThumbnail/UserThumbnail.tsx
we do have a teamAvatar component which uses just a user Id to generate a user image and might help to reduce the number of required props here. 
look into it to see if it can be used here instead, if not, this is fine to keep

2024-02-02 02:34 UTC, yeezick commented on src/components/Notifications/Socket.tsx
> +// }
if this isn't needed we can remove it and always reference this pr instead of keeping dead code in the code

2024-02-02 02:34 UTC, yeezick commented on src/components/Notifications/Socket.tsx
you are now the socket SME 😅

2024-02-02 02:34 UTC, yeezick commented on src/interfaces/ChatInterface.ts
interfaces should also be generally alphabetized
alphabetization makes it easier for us to locate properties we need instead of scanning the whole object for the key we are looking for

2024-02-02 02:34 UTC, yeezick commented on src/interfaces/ChatInterface.ts
use as a general comment

2024-02-02 02:34 UTC, yeezick commented on src/layout/Nav.tsx
> +
remove whitespace
use as a general comment

2024-02-02 02:34 UTC, yeezick commented on src/layout/Nav.tsx
> +    dispatch(setChatRoomActive(false))
i feel like unread count should be determined on the frontend after we fetch all chat messages on load

don't want to make unnecessary api calls but platforms like amplify charge us for each outbound/inbound api request we make

2024-02-02 02:34 UTC, yeezick commented on src/utils/functions/chatLogic.js
> +  return dayjs(timestamp).format('MM/DD/YYYY hh:mm A')
import `generateDayJs` instead of dayjs directly so we only have one instance of it that is loaded with all necessary plugins

2024-02-02 02:49 UTC, yeezick commented
also, please adhere to branch practices for feature branches in future
for new features it should be `feature/BC-ID-desc`

2024-02-02 18:31 UTC, ozggnr commented on src/components/ChatDialog/ChatMemberProfile/ChatMemberProfile.tsx
We don't have this functionality in the beta hifi and but we need to implement member's page in post soft launch. I prefer to remove it completely for now, we'll need  a very detailed members page for post launch so this might not be useful

2024-02-02 18:36 UTC, ozggnr commented on src/components/ChatDialog/ChatRoom/ChatRoom.tsx
> +    // Send message with 'Enter' key, Does not send with 'Enter' + 'Shift'
so if user hits enter, message will be sent, if user hits shift + enter, they will go to the next line. I like this approach, also I believe it's very common but we can discuss absolutely

2024-02-02 18:43 UTC, ozggnr commented on src/components/ChatDialog/UserThumbnail/UserThumbnail.tsx
Oh actually this is something I want to discuss about, I believe we can make this one component since we're using this in different places like calendar, chat, team. this component includes avatar (can be team or single), name and description.

2024-02-02 18:45 UTC, ozggnr commented on src/components/Notifications/Socket.tsx
It was painful but I love it in the end 😁

2024-02-02 19:14 UTC, ozggnr commented on src/layout/Nav.tsx
> +    dispatch(setChatRoomActive(false))
Right now, we don't fetch messages on load, we load chat messages, when user enters a chat room, but unread message field belongs to participant anyway. Let me think about this more how we can handle differently

2024-02-07 23:11 UTC, yeezick requested changes

2024-02-07 23:11 UTC, yeezick commented on src/utils/functions/chatLogic.js
>  export const formatLastMessageTimestamp = lastMessageTimestamp => {
is this function still needed? if not delete it, if yes, can we apply format using dayjs as well?

2024-02-07 23:11 UTC, yeezick commented on src/utils/redux/slices/chatSlice.ts
> +        : dayjs(defaultDate)
using the vanilla dayjs import instead of generateDayJs creating unnecessary extra instances of it

2024-02-07 23:11 UTC, yeezick commented on src/components/ChatDialog/EditChatRoom/EditChatRoom.tsx
> +              />
confused about this map methood, how are we iterating over each participant and then still have to go go into `pp.participant` to get their information? 

seems like its unnecessarily nested?

2024-02-07 23:11 UTC, yeezick commented on src/components/ChatDialog/ChatDialogMain/ChatDialogMain.scss
this comment doesn't look like it was addressed... it should ideally also be applied to scss properties.

2024-02-08 02:16 UTC, ozggnr commented on src/components/ChatDialog/EditChatRoom/EditChatRoom.tsx
> +              />
it's because of participants model
`participants: [
      {
        participant: { type: mongoose.Types.ObjectId, ref: 'User' },
        isAdmin: { type: Boolean, default: false, required: true },
        hasUnreadMessage: { type: Boolean, default: false },
      },
    ]`
 we can change the naming if it's confusing

2024-02-08 02:19 UTC, ozggnr commented on src/utils/functions/chatLogic.js
>  export const formatLastMessageTimestamp = lastMessageTimestamp => {
Actually I missed that, thanks for reminding. This wasn't correct so i created a new one, and also i created dateFormatHelper function to hold these format functions. Let me know if that's ok or need to be moved to another place

2024-02-12 23:42 UTC, yeezick commented on src/components/ChatDialog/ChatMemberProfile/ChatMemberProfile.tsx
if that's the case then delete this.

2024-02-12 23:42 UTC, yeezick commented on src/components/ChatDialog/ChatRoom/ChatRoom.tsx
> +    }
Unresolved

2024-02-13 00:58 UTC, merged