refactor/BC-676 Button Componentization
yeezick/bootcampr pull request #141
Opened 2024-02-12 17:58 UTC by GeoSauer

This PR creates a factory function to easily create reusable, BC branded, flexible buttons.
All styling and state changes have been matched to the Figma HiFi to ensure brand consistency.

2024-02-22 01:20 UTC, yeezick requested changes
god this is so clean i'm impressed. 
so far only paginator buttons are implemented correct? we'll need a follow up ticket to implement app-wide? 

waiting on the removal of unneeded comments and points addressed via DM in discord before approving

2024-02-22 01:20 UTC, yeezick commented on src/interfaces/components/Button.ts
> +//commented icons are still needing to be sourced
let's remove these dead comments here and add them to the ticket for icons instead to keep this file clean

2024-02-22 01:20 UTC, yeezick commented on src/utils/components/Icons.tsx
> +//TODO: linkedIn
same here for all these todos, they're better off living in a ticket than in code

2024-02-22 19:55 UTC, GeoSauer commented
> god this is so clean i'm impressed. so far only paginator buttons are implemented correct? we'll need a follow up ticket to implement app-wide?
> 
> waiting on the removal of unneeded comments and points addressed via DM in discord before approving

Thanks I'm pretty dang happy with it! 
So far nothing is implemented as I wanted to finalize the architecture first. That should be its own ticket spread across several PRs I think.

Comments are removed.
Currently handler is still in place as it is being used where the current Primary/Secondary/Paginator buttons are implemented and will snowball beyond the scope of this ticket if touched. I left a note.

2024-02-24 20:19 UTC, yeezick approved these changes

2024-02-25 05:35 UTC, merged