Refactor/bc 720 display user email on congrats page
yeezick/bootcampr pull request #147
Opened 2024-02-16 21:02 UTC by GeoSauer

This PR accomplishes:

-  language on EmailSentConfirmationPage to adjusted to match Figma 
- adds unverifiedEmail prop to user as there info isn't stored until verification
- email address used to sign up is displayed
- button is present to activate update password flow but currently resends verification email, [BC-753](https://bootcamper.atlassian.net/jira/software/c/projects/BC/boards/2?selectedIssue=BC-753) will finish this off

2024-02-18 19:03 UTC, yeezick commented on src/screens/Auth/SignUp/EmailSentConfirmation/EmailSentConfirmation.tsx
> +  }, [newUserId])
do we need to make an api call to get the user's email? their information should all be stored in redux already after they begin the onboarding flow

want to minimize the amount of api calls make as cloud services like aws charge us for # of requests and size of  requests, inbound and outbound

2024-02-18 19:18 UTC, GeoSauer commented on src/screens/Auth/SignUp/EmailSentConfirmation/EmailSentConfirmation.tsx
> +  }, [newUserId])
So this is the product of a weird series of events, and may be due to my new exposure to redux. From what I could tell the user isn't fully stored until after they confirm their email? 

When trying to pull user info from that page it was returning undefined, and if you check out the commit where I added the `unverifiedEmail` email prop you can see that I added that prop and the means to access it. It worked and displayed properly but did not persist on refresh.

2024-02-18 19:18 UTC, GeoSauer commented on src/screens/Auth/SignUp/EmailSentConfirmation/EmailSentConfirmation.tsx
> +  }, [newUserId])
Maybe the issue is that most things revolve around an authUser currently and they aren't signed in at this point?

2024-02-22 01:24 UTC, yeezick commented on src/screens/Auth/SignUp/EmailSentConfirmation/EmailSentConfirmation.tsx
> +  }, [newUserId])
ahh i see. i thought they were immediately logged in afterword but i see the issue now. 

maybe another workaround is to dispatch the user's email to redux after they click the sign up button? but to only store the user email at that point 

this way we can still save ourselves from the api call

2024-02-22 01:28 UTC, yeezick requested changes
this is good to go after my response to the last comment

2024-02-22 19:56 UTC, GeoSauer commented on src/screens/Auth/SignUp/EmailSentConfirmation/EmailSentConfirmation.tsx
> +  }, [newUserId])
Is that something we want to add to this ticket or will it be its own?

2024-02-24 21:07 UTC, yeezick commented on src/screens/Auth/SignUp/EmailSentConfirmation/EmailSentConfirmation.tsx
> +  }, [newUserId])
i think it should be in this ticket as it directly relates to it

basically just replacing the useEffect from the email confirmation page with a selector for the user's email & dispatching the call to update the user slice on success response from the sign in controller

2024-02-28 01:01 UTC, yeezick approved these changes

2024-02-29 01:22 UTC, merged