Feature/bc 261 ability to update credentials
yeezick/bootcampr pull request #17
Opened 2022-11-18 17:07 UTC by zendrias

Sign in form was also merged into this branch from my computer, so this has the code for both...

During this sprint I...

- Created a **setting array where each item is a setting dropdown** in a separate module. We can easily add more setting dropdowns in the future using this method. (Keeps the code DRY too!) (Check it out here => [src/screens/AccountSettings/helper/data.ts](https://github.com/yeezick/bootcampr/compare/feature/BC-261-ability-to-update-credentials?expand=1#diff-407f3194a893d4d3cc4560ac35f220c29d8d11dda0f11bc28a77673a71c8050d))
- Added some poor styling lol
- Users can toggle whether to see their password while they are updating their credentials 
- The **authFormData** variable changes its initial state depending on which dropdown is open
- Only one dropdown can be open at a time, as per the Jira ticket requirements
- Button is disabled until the user fills out the form and addresses errors
*Note
I changed the following module to TypeScript, as it was giving me type errors.
[src/utilities/api/users.js → src/utilities/api/users.ts](https://github.com/yeezick/bootcampr/compare/feature/BC-261-ability-to-update-credentials?expand=1#diff-8491ed015b0166f70822a5f214cfebeb0dddb1771c143fa5e7fcdf60758b35b0)

2022-11-20 19:12 UTC, HectorIlarraza requested changes
Very impressive work Zena, had to really do some HW to see how you wrote all this. Just a couple of things to change and questions I'll need from you to approve.

2022-11-20 19:12 UTC, HectorIlarraza commented on src/screens/SignIn/SignIn.module.css
> +.sign_in_container {
ABC order

2022-11-20 19:12 UTC, HectorIlarraza commented on src/screens/AccountSettings/AccountSettings.tsx
> +              onClick={() => handleToggleDropdown(val)}
is the anon function needed, just curious.

2022-11-20 19:12 UTC, HectorIlarraza commented on src/screens/AccountSettings/helper/FormErrors.tsx
> +    <>
not sure if its ur prettier doing this but can you refactor this to make it easier to read the way its displayed now is kinda hard to follow without double checking

2022-11-20 19:12 UTC, HectorIlarraza commented on src/screens/AccountSettings/helper/UpdateFeedback.tsx
> +interface UpdateCredentialsFeedbackMessageProps {
can be moved into the "AccountSettingsInterface.tsx" file and imported here

2022-11-27 00:05 UTC, yeezick commented on package.json
> +    "node-sass": "^7.0.3"
just curious, did we have to make it a dev dependency? 
will it be safe to build in production without this package?

2022-11-27 00:15 UTC, yeezick commented on src/App.tsx
> +            <Route index element={<Projects />} />
Yeah this is interesting! please feel free to mention it at stand up so we can all learn something

2022-11-27 00:18 UTC, yeezick commented on src/screens/AccountSettings/AccountSettings.module.css
> +* {
We have to discuss whether or not to change practices as a team before implementing them. 
If we choose not to go that route, you would lose time in refactoring

2022-11-27 00:20 UTC, yeezick commented on src/screens/AccountSettings/AccountSettings.module.css
> +.account_settings_container {
same note here, all files currently use "class-name", if you would like to suggest a change to our style guide please bring it up to the team first.

2022-11-27 00:20 UTC, yeezick commented on src/screens/AccountSettings/AccountSettings.tsx
> +
whitespace

2022-11-27 00:23 UTC, yeezick commented on src/screens/AccountSettings/AccountSettings.tsx
> +const AccountSettings = ({ }: AccountSettingsProps): JSX.Element => {
if there are no expected props we can leave it as an empty `()`

2022-11-27 00:27 UTC, yeezick commented on src/screens/AccountSettings/AccountSettings.tsx
> +              className={`${dropdownModes[val as keyof DropDownSettings] ? styles.arrow : styles.active_arrow}`}>
i'm curious about the `as keyof` keyword, please teach us about it in stand up

2022-11-27 00:30 UTC, yeezick commented on src/screens/AccountSettings/forms/AuthSettingsFormDropdown/AuthFormInput.tsx
> +  const [showPassword, setShowPassword] = useState<boolean>(PasswordInput ? false : true)
if i'm reading this right, this would set "showPassword" to on the inital declaration of this state. 
let the user select when to toggle it manually by clicking a button. 
another cool feature i've seen is showing the user the password when they click on it and hiding it again when they unfocus

2022-11-27 00:31 UTC, yeezick commented on src/screens/AccountSettings/forms/AuthSettingsFormDropdown/AuthFormInput.tsx
> +      <label className={styles.auth_form_label} htmlFor={`${type}_input`}>{field}*</label>
you must be coding in python or something on the side lol, keep to camelCase. there aren't many use cases for dashes in JS

2022-11-27 00:32 UTC, yeezick commented on src/screens/AccountSettings/forms/AuthSettingsFormDropdown/AuthFormInput.tsx
> +export default AuthFormInput;
no export defaults and also no newline at end of file

2022-11-27 00:34 UTC, yeezick commented on src/screens/AccountSettings/forms/AuthSettingsFormDropdown/AuthSettingsFormDropdown.tsx
> +  const VALID_EMAIL_REGEX = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;
this regex is thorough! add a comment here like "only allows ab@."

2022-11-27 00:37 UTC, yeezick commented on src/screens/AccountSettings/forms/AuthSettingsFormDropdown/AuthSettingsFormDropdown.tsx
> +    fetchAPI: async () => emailDropDownActive ? await updateUsersEmail(authFormData, id) : await updateUsersPassword(authFormData, id),
love this, clever. see if you can figure out how to avoid "any" type on "temp" 
temp is also not very semantic, not sure what it refers to

2022-11-27 00:38 UTC, yeezick commented on src/screens/AccountSettings/forms/AuthSettingsFormDropdown/AuthSettingsFormDropdown.tsx
> +
whitespace between consts

2022-11-27 00:38 UTC, yeezick commented on src/screens/AccountSettings/forms/AuthSettingsFormDropdown/AuthSettingsFormDropdown.tsx
> +    let temp: any = { ...authFormData }
same note from before, make temp descriptive and remove any type

2022-11-27 00:39 UTC, yeezick commented on src/screens/AccountSettings/forms/AuthSettingsFormDropdown/AuthSettingsFormDropdown.tsx
> +        < FormErrors VALIDATION_HELPERS={VALIDATION_HELPERS} emailDropDownActive={emailDropDownActive} authFormData={authFormData} />
fix your editor, it doesn't seem to be formatting correctly on this opening tag or for the new line at the end of this file

2022-11-27 00:42 UTC, yeezick commented on src/screens/AccountSettings/helper/FormErrors.tsx
> +    <>
I agree, it also seems like we're repeating a lot of logic here, there might be a way to create some kind of 'error-generator' so that this file ages & scales better (if or when error cases grow)

2022-11-27 00:46 UTC, yeezick commented on src/screens/AccountSettings/helper/UpdateFeedback.tsx
> +interface UpdateCredentialsFeedbackMessageProps {
ok so this makes me think of what would be best practice for our types
generally, if a variable is intended to be shared it should live within a shared file
in this case, it doesn't seem to be the case so would it be appropriate to live here or still worth relocating?
Next question would be whether or not it'd be worth to create a shared space (file or folder) to move our types into within the helper directory

2022-11-27 01:01 UTC, yeezick commented on src/screens/AccountSettings/helper/UpdateFeedback.tsx
> +      {updateStatus === 'unauthorized' && <p>❌ Wrong Password</p>}
the answer for an 'error-generator' could be a switch statement
if a case does not have a "break" keyword i'm pretty sure it just cascades to the next case

2022-11-27 01:02 UTC, yeezick commented on src/screens/AccountSettings/helper/data.ts
> +
whitespace

2022-11-27 01:02 UTC, yeezick commented on src/screens/AccountSettings/helper/data.ts
> +
nice file structure

2022-11-27 01:03 UTC, yeezick commented on src/screens/SignIn/SignIn.module.css
> +}
no new line

2022-11-27 01:04 UTC, yeezick commented on src/screens/SignIn/SignIn.tsx
> +  const [formData, setFormData] = useState<SignInInterface>({ email: "", password: "" })
add the default state for formData to the data.ts file you created

2022-11-27 01:04 UTC, yeezick commented on src/utilities/types/AccountSettingsInterface.ts
> +
empty interface

2022-11-27 01:05 UTC, yeezick commented on src/utilities/types/AccountSettingsInterface.ts
> +    emailsMatch: (temp: any | EmailFormData) => boolean;
same note about temps and any

2022-11-27 01:09 UTC, yeezick commented
@zendrias great work and good PR, a little too clever!! but always an opportunity to learn something in there. 
@HectorIlarraza great review as well my friend

Please be mindful the [sign-in PR ](https://github.com/yeezick/bootcampr/pull/6) is piggybacking on this one. make sure to merge and close sign in before merging this one. 

I trust Hector to finish the review on this PR, no further approval needed from me.

2022-11-30 21:54 UTC, zendrias commented on package.json
> +    "node-sass": "^7.0.3"
It wasn't working on my computer for some reason and I was following some stack overflow forum response to fix it. It had me do this, I meant to put it back before pushing, I just forgot...

2022-11-30 21:55 UTC, zendrias commented on src/screens/AccountSettings/AccountSettings.module.css
> +* {
I removed it

2022-12-05 00:25 UTC, HectorIlarraza requested changes
Incredible work here fixing everything that was requested Zena, Just one more suggestion on my part and I can approve you for the last phase.

2022-12-14 22:46 UTC, zendrias commented on src/screens/AccountSettings/helper/validation.ts
> +interface FormDataCopy {
Done!

2022-12-14 23:34 UTC, HectorIlarraza approved these changes
Everything is all good Zena, approved!

2022-12-14 23:39 UTC, merged