Feature/bc 783 develop payments flow
yeezick/bootcampr pull request #173
Opened 2024-03-13 01:10 UTC by yeezick

Accomplishes [BC-783: develop payments flow](https://bootcamper.atlassian.net/jira/software/c/projects/BC/boards/2?selectedIssue=BC-783)
*

2024-03-13 15:51 UTC, ozggnr requested changes

2024-03-13 15:51 UTC, ozggnr commented on src/components/AccountDropdown.tsx/AccountDropdown.tsx
> +      navigate('/payment/checkout')
I might have missed this but are we planning to implement the checkout page later, or does this route already exist?

2024-03-13 15:58 UTC, yeezick commented on src/components/AccountDropdown.tsx/AccountDropdown.tsx
> +      navigate('/payment/checkout')
I had this checkout page just a placeholder to test the stripe integration 

Instead, the button to complete payment will call an api which will return a stripe-hosted URL and automatically redirect the user to stripe to complete checkout. 

After payment, the user will be rerouted to the success screen. 

Basically we do not own the checkout screen at this time

2024-03-13 16:01 UTC, ozggnr approved these changes

2024-03-14 17:03 UTC, ozggnr approved these changes

2024-03-14 19:16 UTC, merged