Refactor/BC-345-refactor-signup-register-user-info-css-to-scss
yeezick/bootcampr pull request #18
Opened 2022-11-30 18:58 UTC by jasonmar08

Refactored CSS for `RegisterUserInfo` and `SignUp` screens to SCSS format, utilizing mixins and variables.

2022-12-01 15:12 UTC, HectorIlarraza requested changes
Fantastic SCSS usage for a first-time application @jasonmar08 just removed those CSS files and I can move it to the next phase.

2022-12-01 15:12 UTC, HectorIlarraza commented on src/screens/RegisterUserInfo/dist/RegisterUserInfo.css
> +/* --------------------------- */
If I'm not mistaken this is the original CSS file you used as a template to create the SCSS file above correct? If so make sure to remove this file for any future SCSS refactor tickets to avoid possible confusion for reviewers I almost thought you missed a file lol.

2022-12-01 15:12 UTC, HectorIlarraza commented on src/screens/SignUp/SignUp.scss
> +@mixin input-fields($padding, $width) {
chef's kiss 👨🏽‍🍳 🤌🏾 right here @mixin & @include

2022-12-01 15:12 UTC, HectorIlarraza commented on src/screens/SignUp/dist/SignUp.css
> +/* --------------------------- */
Same for this file to be removed

2022-12-01 18:53 UTC, jasonmar08 commented
- Removed sass compiler extension and dist folder created by it
- Also fixed bug related to RegisterUserInfo screen where it did not updated the isSuccess uiStatus to `false` after form submission

2022-12-02 00:35 UTC, HectorIlarraza approved these changes
Everything is now perfect Jason, approved for the next phase.

2022-12-03 17:44 UTC, yeezick commented on src/screens/RegisterUserInfo/RegisterUserInfo.scss
> +$color-btn-hover: rgb(79, 127, 169);
above and beyond with variables and mixins! I actually haven't learned about them yet and would love to learn from you

2022-12-03 17:46 UTC, yeezick commented on src/screens/RegisterUserInfo/RegisterUserInfo.scss
> +  padding: 0.3rem 0.4rem;
let's resort to `px` for now to stay consistent and in control. rem, em, percentages, etc are relative and can provoke styling defects

2022-12-03 17:47 UTC, yeezick commented on src/screens/SignUp/SignUp.scss
> +$color-btn-active: rgb(54, 91, 123);
i noticed some of these variables are repeated, see if you can migrate them to a shared scss sheet maybe in a new `styles/` directory. This may be the beginning of our component library

2022-12-03 17:49 UTC, yeezick requested changes
Awesome SCSS implementation! Well formatted and readable. Added minor thoughts here but functionally great work.

2022-12-03 17:51 UTC, jasonmar08 commented on src/screens/SignUp/SignUp.scss
> +$color-btn-active: rgb(54, 91, 123);
Yeah, I was thinking the same thing and preferred to do that, but wasn't sure if we were ready to create a new main styles directory

2022-12-03 17:54 UTC, yeezick commented on src/screens/SignUp/SignUp.scss
> +$color-btn-active: rgb(54, 91, 123);
@jasonmar08 trust ur gut, i trust ur code. anything questionable can be caught here and if i'm not reviewing don't hesitate to ping me

2022-12-08 06:44 UTC, jasonmar08 commented
- Created a global scss directory which would contain global styling variables, mixins, functions, etc.

2022-12-08 12:02 UTC, yeezick approved these changes
Excellent work Jason.

2022-12-08 16:39 UTC, merged