feature/BC-785-frontend-3-day-availability-requirement
yeezick/bootcampr pull request #185
Opened 2024-03-27 07:09 UTC by HectorIlarraza

### Feature: Implement 3-Day Availability Requirement

This ticket aims to enforce a 3-day availability requirement during the onboarding process on the platform.

### Changes Made:

1. 3-Day Availability Requirement Implementation:

- Implemented functionality to enforce a 3-day availability requirement during the onboarding process.
- Users are required to select a minimum of 3 days of the week, with each day having at least 60 minutes of availability.

2. Prevent Proceeding with Insufficient Availability:

- Prevented users from proceeding with onboarding if they have not selected a minimum of 3 days of availability.
- Users will be notified and blocked from progressing if the selected availability is less than 3 different days.

3. Banner Addition for Informing Users:

- Added a banner to inform users about the 3-day availability requirement during the availability selection process.
- The banner explains the importance of selecting at least 3 days of availability.

### Review Notes:

Successfully implemented the 3-day availability requirement during onboarding. Users are now required to select at least 3 days of availability, with each day having a minimum of 60 minutes. Additionally, added a banner to inform users about this requirement and prevented them from proceeding if the selected availability is insufficient.

### Deployment Notes:

No specific deployment requirements or changes are needed for this feature implementation. The updates will be included in the next deployment cycle.

**_Please review the changes and provide feedback as needed. Thank you!_**

2024-03-28 00:15 UTC, ozggnr requested changes

2024-03-28 00:15 UTC, ozggnr commented on src/screens/Onboarding/SetupAvailability.tsx
> +            const startTime = moment(slot[0], 'h:mm A')
Could we use 'dayjs' here instead of 'moment'?  As far as I know, 'moment.js' is deprecated, can cause issues later

2024-03-31 17:06 UTC, HectorIlarraza commented on src/screens/Onboarding/SetupAvailability.tsx
> +            const startTime = moment(slot[0], 'h:mm A')
ahh gotcha will do!

2024-04-01 20:50 UTC, ozggnr requested changes

2024-04-01 20:50 UTC, ozggnr commented on src/screens/Onboarding/SetupAvailability.tsx
> +            const endTime = dayjs(slot[1], 'LT')
could you create a helper function for this `dayjs` method

2024-04-08 23:38 UTC, ozggnr approved these changes

2024-04-08 23:39 UTC, merged