Feature/bc 308 create roles
yeezick/bootcampr pull request #26
Opened 2022-12-11 20:46 UTC by yeezick

Completes [BC-308: create roles](https://bootcamper.atlassian.net/browse/BC-308?atlOrigin=eyJpIjoiN2Y5YWU1YmUzZDY0NGU3M2FiYTExMWUwYmMxY2YxNDMiLCJwIjoiaiJ9)
This ticket is meant to be tested and merged with its [backend counterpart](https://github.com/yeezick/bootcampr-backend/pull/29)

- restructures interfaces to support role types (engineering, design, etc) 
- CreateRole component handles the form for the new role 
- ViewRoles handles rendering the roles of the project form, which is updated after a role is created 
- Also creates some helper files for StringUtils, starting with capitalizing a title

2022-12-12 00:14 UTC, mendo94 requested changes
Wow your Typescript abilities have grown immensly. Can;t wait to merge your branch and get some breakthroughs over here!! Also, getting a few errors and was wondering if you were getting them on your end or not when rendering the edit project screen.

2022-12-12 00:14 UTC, mendo94 commented on src/screens/Roles/ViewRoles.tsx
> +const MapRoles = ({ role }: MapRolesProps) => {
Getting an 'each child should have a unique key prop' error for mapRoles

2022-12-12 00:14 UTC, mendo94 commented on src/screens/Roles/ViewRoles.tsx
> +const MapInterestedApplicants = ({ applicants }: InterestedApplicantsProps) => {
Getting an 'each child should have a unique key prop' error for MapInterested applicants

2022-12-12 00:14 UTC, mendo94 commented on src/screens/CreateProject/EditProject.tsx
> +import { CreateRole } from '../Roles/CreateRole';
This component is giving 'a component is changing a controlled input to be uncontrolled' error

2022-12-12 00:14 UTC, mendo94 commented on src/screens/CreateProject/EditProject.tsx
>  import { getOneUser } from '../../utilities/api/users';
Are you getting the same error when the edit project screen loads? "Cast to ObjectId failed for value "undefined" (type string) at path "_id" for model "User"" because of the id being undefined, it will not let me complete the create role request, just crashes with error "Cannot convert undefined or null to object"

2022-12-12 00:14 UTC, mendo94 commented on src/utilities/types/ProjectInterface.ts
> +  roles: {
Wow, hopefully this is the fix to my error - putting interface[] on each variable!!

2022-12-12 00:14 UTC, mendo94 commented on src/screens/CreateProject/EditProject.tsx
>  import { getOneUser } from '../../utilities/api/users';
<img width="1422" alt="Screen Shot 2022-12-11 at 7 11 50 PM" src="https://user-images.githubusercontent.com/94413237/206937491-6cd6a3bb-7dd3-4e30-8136-9f0cd64f7866.png">

2022-12-19 23:06 UTC, yeezick commented on src/screens/CreateProject/EditProject.tsx
> +import { CreateRole } from '../Roles/CreateRole';
This is an issue with `<EditProject />`'s file input, after commenting it out the warning went away. 
It's because that input doesn't have a value but its value changes with state; the recommended approach is to [set this input's value via useRef](https://reactjs.org/docs/uncontrolled-components.html#the-file-input-tag)

Instead, we should open a bug ticket or add it to the AC of Koffi's profile image PR

2023-02-02 01:06 UTC, yeezick commented
This PR is considered outdated based on the new direction of the app. 
This PR has not resolved all of its conflicts and is not yet fully functioning. 
Only being merged to close the PR and preserve the work in case it's ever needed again.

2023-02-02 01:07 UTC, merged