Feature/bc 260 profile images
yeezick/bootcampr pull request #29
Opened 2022-12-18 19:26 UTC by Bestnogm1

Added feature to be able to add profile images and and edit it as well

2022-12-27 18:23 UTC, mendo94 requested changes
minor fixes, amazing work as always!!

2022-12-27 18:23 UTC, mendo94 commented on src/screens/PreviewsUserImage/PreviewsUserImage.tsx
> +export const PreviewsUserImage = ({ previewImage, authUser }: any) => {
can any be changed to a specific type?

2022-12-27 18:23 UTC, mendo94 commented on src/utilities/api/users.ts
> +    console.log(res.data);
good to remove

2022-12-28 00:43 UTC, yeezick commented on src/screens/RegisterUserInfo/RegisterUserInfo.tsx
> +
since it's short we can get rid of the whitespace around the `if`. we want to think of code like a book, sometimes it makes sense to have short paragraphs (separating bits of logic), but when the whole block is 1 short paragraph, we can just let it read

2022-12-28 00:47 UTC, yeezick commented on src/utilities/api/users.ts
> +  id: string | undefined,
string shouldn't be undefined, in this function, if it didn't have the id it would fail
haven't seen ur backend pr but nice `imageWasUpdated` key to the req.body `B^)`  nice n orthogonal

2022-12-28 00:48 UTC, yeezick commented
nice pr
<img src="https://media.giphy.com/media/NEvPzZ8bd1V4Y/giphy.gif" />

2022-12-28 16:24 UTC, mendo94 commented on src/utilities/api/users.ts
> +  id: string | undefined,
the backend PR for this ticket was already merged into dev two weeks ago I believe

2023-02-22 23:49 UTC, closed without merging