Feature/bc 344 send email verification link after user signup
yeezick/bootcampr pull request #31
Opened 2022-12-31 23:33 UTC by jasonmar08

Created email verification functionality with handling of the following cases:

- send new user an email with a verification link containing the token after sign up
- verify the user and automatically sign them in after clicking the email url (link with token has 30 second expiration for testing purposes, but will refactor to 1 hour expiration time for development)
- if a user did not verify their account, but tries to log in, don't sign them in and automatically send them a new email with a new token url
- if user tries to click an expired verification url, don't verify them and navigate them to a screen saying the url is expired with the option to resend a new link

2022-12-31 23:59 UTC, mendo94 requested changes
Please merge dev into your branch to resolve the conflicts

2023-01-03 23:08 UTC, mendo94 requested changes
![Screen Shot 2023-01-03 at 6 05 33 PM](https://user-images.githubusercontent.com/94413237/210455998-eb3a9f68-9e45-4397-a34f-9b66ed91ba4d.png)

Oh nooo I wanted to ttest this out so bad, getting above error when I try to sign up with a new email. It is a 400 response but also received a toast message that the email was sent successfully so also will need to set up error handling to say the email was not sent successfully if the query returns a 400 response.

2023-01-04 01:25 UTC, yeezick commented on src/screens/SignIn/SignIn.tsx
> +              <p dangerouslySetInnerHTML={{ __html: alertBanner.txt }} />
do we need to do this? not inclined to things with the word "dangerous" in them 
gives me PTSD of when I did this at my first job
what about `<p>{alertBanner.text}</p>`?

2023-01-04 01:26 UTC, yeezick commented on src/screens/EmailVerify/EmailVerify.tsx
> +  )
return null instead

2023-01-04 01:26 UTC, yeezick commented on src/screens/ExpiredLink/ExpiredLink.scss
> +/* --------------------------- */
not necessary

2023-01-04 01:26 UTC, yeezick commented on src/screens/RegisterUserInfo/RegisterUserInfo.scss
>  /* --------------------------- */
not necessary

2023-01-04 01:26 UTC, yeezick commented on src/screens/RegisterUserInfo/RegisterUserInfo.tsx
> +        ) : ''
return null instead

2023-01-04 01:26 UTC, yeezick commented on src/screens/SignIn/SignIn.tsx
> +  const [alertBanner, setAlertBanner] = useState<any>({ status: false,
we can type this state

2023-01-04 01:26 UTC, yeezick commented on src/screens/SignIn/SignIn.tsx
> +          ) : ''
return null

2023-01-04 01:27 UTC, yeezick commented on src/screens/SignIn/SignIn.tsx
> +        <form className={styles.sign_in_form} onSubmit={handleSubmitForm}>
no snake_case styles

2023-01-04 01:27 UTC, yeezick commented on src/screens/SignUp/SignUp.scss
what are these for?

2023-01-04 01:28 UTC, yeezick commented on src/screens/SignUp/SignUp.tsx
> +  const [alertBanner, setAlertBanner] = useState<any>({ status: false, txt: '' })
same here about typing since we're passing the initial state
can we use `text` instead of `txt`?

2023-01-04 01:29 UTC, yeezick commented on src/screens/SignUp/SignUp.tsx
> +        ) : ''
last null

2023-01-04 01:31 UTC, yeezick commented on src/utilities/redux/slices/users/userSlice.ts
> +        // state.auth.user = action.payload;
dead code

2023-01-04 01:32 UTC, yeezick commented on src/utilities/types/UserInterface.ts
> +      message?: string | any;
can message be string or object?

2023-01-04 01:32 UTC, yeezick requested changes
tedious linting comments, beside that, solid PR 💯 👍

2023-01-04 01:35 UTC, yeezick commented
testing discord webhook

2023-01-04 01:36 UTC, yeezick commented
testing 2

2023-01-04 01:59 UTC, jasonmar08 commented on src/screens/SignIn/SignIn.tsx
> +              <p dangerouslySetInnerHTML={{ __html: alertBanner.txt }} />
I used it because I was sending HTML in the response from the backend so the alert message can contain a link to the sign up page:
`if (!user) {
      return res.status(299).json({
        invalidCredentials: true,
        message: `That Bootcampr account doesn't exist. Enter a different account or <a href='/sign-up'>create a new one</a>.`,
      });
    }`

But I was looking right now and seems like you can add a sanitizer like dompurify to the HTML that will safeguard the effects of dangerously. Any other alternatives you may know of to parse HTML to JSX?

https://javascript.plainenglish.io/dangerouslysetinnerhtml-in-react-js-explained-4dfc3b80be82

2023-01-09 20:14 UTC, jasonmar08 commented on src/screens/SignIn/SignIn.tsx
> +        <form className={styles.sign_in_form} onSubmit={handleSubmitForm}>
This will be refactored in @zendrias's ticket

2023-01-09 20:17 UTC, jasonmar08 commented on src/utilities/types/UserInterface.ts
> +      message?: string | any;
changed `any` to `object`

2023-02-16 02:32 UTC, yeezick approved these changes

2023-02-16 02:33 UTC, merged