Feature/bc 300 implement create project
yeezick/bootcampr pull request #4
Opened 2022-10-18 20:26 UTC by mendo94

Tried to get this done asap because this ticket is blocking a lot of other tickets, plus I know you will have much for me to change/fix. Was not too fixated on styling - just getting the api call to work and the schema to match the user stories. I was only focused on getting the project to post to the database - NOT the roles because I know that is coming in a later ticket.

2022-10-24 13:49 UTC, yeezick commented on src/screens/CreateProject/CreateProject.tsx
> +    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>,
good idea

2022-10-24 13:50 UTC, yeezick commented on src/screens/CreateProject/CreateProject.tsx
> +  const [createProjects, setCreateProjects] = useState<any[]>([]);
we should find out the specific type for the `createProjects` array 
also curious about the `File` type, where's it coming from?

2022-10-24 14:09 UTC, yeezick commented on src/screens/CreateProject/CreateProject.tsx
> +          <label htmlFor="status">
i think we should discuss as a team about the best way to create label/input pairs. above you wrote them as:
```
<label>i am label</label>
<input />
```
and here they're written as 
```
<label>
    i am label
    <input />
</label>
```

I personally prefer the first format because it gives us control of the input & label separately, however the second format eliminates the need for the "htmlFor" and the "id" attributes ("id" bubbles up to the global scope of the browser html and is an opportunity for clashes if there are similar id's on other files

2022-10-24 14:12 UTC, yeezick commented on src/screens/CreateProject/CreateProject.tsx
> +          <label htmlFor="status">
Also, I think this div would call for a radio button over checkbox

2022-10-25 00:07 UTC, yeezick commented on src/screens/CreateProject/CreateProject.tsx
> +        </div>
add some text below this input in red font to let us know this feature is not built quite yet, but we can keep it on the gui

2022-10-25 00:08 UTC, yeezick commented on src/screens/CreateProject/CreateProject.tsx
> +  const [createProjects, setCreateProjects] = useState<any[]>([]);
once you git pull with development, you should have the Project Interface in `/src/utilities/Interfaces/ProjectInterface.ts`

2022-10-25 00:09 UTC, yeezick requested changes
resolve conversations above, ping me to test, and should be ready to merge!

2022-10-25 01:44 UTC, yeezick commented on src/screens/CreateProject/CreateProject.tsx
> +  const [createProjects, setCreateProjects] = useState<any[]>([]);
let's also rename `createProjects` to `projectForm` and set the initial state to an empty or dummy object instead

2022-10-26 02:29 UTC, mendo94 commented on src/screens/CreateProject/CreateProject.tsx
> +        <label htmlFor="project-owner">Project Owner</label>
Waiting to test this out better once the sign in screen is built

2022-10-26 02:30 UTC, mendo94 commented on src/screens/CreateProject/CreateProject.tsx
> +          type="email"
from yesterday's convo, yes, it returns a string

2022-10-26 02:31 UTC, mendo94 commented on src/screens/CreateProject/CreateProject.tsx
> +          <label htmlFor="status">
Changed to radio button and moved the labels to <label>i am label</label>
<input /> since I do not need the checkbox here.

2022-10-26 02:32 UTC, mendo94 commented on src/screens/CreateProject/CreateProject.tsx
> +        </div>
red text added here

2022-10-29 23:03 UTC, yeezick commented on src/screens/CreateProject/CreateProject.tsx
> +  const [createProjects, setCreateProjects] = useState<any[]>([]);
This conversation was not resolved.

2022-10-29 23:04 UTC, yeezick commented
@mendo94 one last item to resolve. also, i noticed the email on the project details page is camelcased, is it returning like that from the api?

2022-10-31 21:51 UTC, mendo94 commented on src/screens/CreateProject/CreateProject.tsx
> +  const [createProjects, setCreateProjects] = useState<any[]>([]);
This was resolved, not sure why it didn't show up here that it was changed.

2022-10-31 21:53 UTC, mendo94 commented
It was just some styling getting passed from a different component. I removed it - but it was not returning like that from the api to answer your question.

2022-11-01 02:32 UTC, mendo94 commented
Changed project interface so the useState could pass the data coming from the api and took out. the empty array. Needed to refactor all of the project components due to this change. Ready to be reviewed again.

2022-11-01 22:57 UTC, yeezick commented on src/screens/CreateProject/CreateProject.tsx
> +  }, [setProjectForm]);
since setProjectForm is the setter function, it's value would never change which is why this works but i'm not sure it's best practice... 
do we need anything in the dependency array at all?

2022-11-01 23:01 UTC, yeezick commented on src/screens/Projects/ProjectDetails.tsx
> +    id: '',
i see now about having to recreate to rewrite this object so many times... sorry!

If I could suggest creating a js file at `src/utilities/constants.js` and export this object as a variable from there, we would make the dummy object easier to maintain by only having 1 place to update it as well as make this file easier on the eyes

2022-11-05 15:35 UTC, mendo94 commented on src/screens/Projects/ProjectDetails.tsx
> +    id: '',
Cleaned up the project files by moving the dummy object into a constants js file

2022-11-05 15:41 UTC, mendo94 commented on src/screens/CreateProject/CreateProject.tsx
> +  }, [setProjectForm]);
took out dependency

2022-11-05 20:26 UTC, yeezick submitted a review, later dismissed
excellent work rina! this is ready to go!

2022-11-05 20:27 UTC, yeezick approved these changes

2022-11-05 20:38 UTC, merged