Feature/bc 450 chat dialog
yeezick/bootcampr pull request #44
Opened 2023-04-13 21:12 UTC by jasonmar08

- Structured out the main components for the chat dialog with some API calls already being made
- Need to fix profilePicture error
- Will create a new ticket to incorporate the functionality

2023-04-18 18:31 UTC, yeezick commented on src/components/ChatDialog/ChatDialogMain/ChatDialogMain.tsx
> +  // const [chatHeader, setChatHeader] = useState('')
remove dead code

2023-04-18 18:31 UTC, yeezick commented on src/components/ChatDialog/ChatDialogMain/ChatDialogMain.tsx
> +import { useAppDispatch } from '../../../utilities/redux/hooks'
use import aliases

2023-04-18 18:32 UTC, yeezick commented on src/components/ChatDialog/ChatDialogMain/ChatDialogMain.tsx
> +              onClick={() => handleComposeMessage()}
no need for anonymous functions if no params are needed
`onClick={handleComposeMessage}`

2023-04-19 17:39 UTC, yeezick requested changes
Honestly, excellent PR! I only have some comments around legibility but the overall logic is very solid! Good work! Let's connect on the gnarly conditionals if necessary

2023-04-19 17:39 UTC, yeezick commented on src/components/ChatDialog/ChatDialogMain/ChatDialogMain.tsx
> +          {!showMessages && showChats ? (
Can we brainstorm a way to make these gnarly conditionals easier to read? I'm open to contemplating it with you

2023-04-19 17:39 UTC, yeezick commented on src/components/ChatDialog/Conversations/Conversations.scss
> +      height: 35px;
Nice alphabetization ty

2023-04-19 17:39 UTC, yeezick commented on src/components/ChatDialog/Conversations/Conversations.tsx
> +                  {participants.length > 2 ? (
Same here, these are gnarly and I see that we ask the same conditional twice

2023-04-19 17:39 UTC, yeezick commented on src/components/ChatDialog/Messages/Messages.tsx
> +import { formatTimestamp } from '../../../utilities/functions/utilityFunctions'
Alias imports

2023-04-19 17:39 UTC, yeezick commented on src/components/ChatDialog/NewChatRoom/NewChatRoom.tsx
> +    setProjectMembers([...designers, ...engineers])
Just to let u know, designers and engineers here will be spread out based on its current state, not based on the new values you're setting above it here

2023-04-19 17:39 UTC, yeezick commented on src/utilities/functions/utilityFunctions.js
> +  hours = hours ? hours : 12
Since we're defining hours with let and then modifying it directly afterward, let's group them together

2023-04-19 17:39 UTC, yeezick commented on src/utilities/functions/utilityFunctions.js
> +  hours = hours ? hours : 12
So we can track the assignment more easily

2023-04-30 05:34 UTC, yeezick commented on src/components/ChatDialog/Conversations/Conversations.tsx
> +        console.log('results: ', res)
console log

2023-04-30 05:35 UTC, yeezick commented on src/components/ChatDialog/Conversations/Conversations.tsx
> +            _id,
rename _id to be semantic, i think here it is a conversation/chat id?

2023-04-30 05:36 UTC, yeezick commented on src/components/ChatDialog/Conversations/Conversations.tsx
> +          ({ _id, participants, groupName, groupPhoto, lastMessage }) => (
same here for _id, you can reassign it during destructures with `{_id: chatId}`

2023-04-30 05:37 UTC, yeezick commented on src/components/ChatDialog/Conversations/Conversations.tsx
> +            :{' '}
`:{' '}` may be leftover from previous implementation

2023-04-30 05:40 UTC, yeezick commented on src/layout/Nav/Nav.tsx
> +            {visibleChat ? <ChatDialogMain /> : ''}
can be cimplified to `visibleChat && <ChatDialogMain />`

2023-05-01 22:31 UTC, jasonmar08 commented on src/components/ChatDialog/Conversations/Conversations.tsx
> +            :{' '}
this is automatically added when I remove it

2023-05-04 19:20 UTC, yeezick approved these changes

2023-05-04 19:20 UTC, yeezick commented
holy moly +1000 lines!!

2023-05-05 23:58 UTC, merged