Feat/redux tool kit/bc 319
yeezick/bootcampr pull request #5
Opened 2022-10-19 21:10 UTC by Bestnogm1

- added redux tool kit
- initialize the redux store 
- initialize redux state 
- create UnserInterface for landing jsx
-

2022-10-19 21:21 UTC, yeezick commented on src/api/users.js
> +  let testId = '634f0bfa570c7584a7c6a0e5';
Instead of hardcoding a testID, on the react component that is calling this function, call the `getAllUsers` api first, and select the ID of the first user in that array

2022-10-19 21:23 UTC, yeezick commented on src/app/features/users/userSlice.tsx
> +  users: getOneUser(),
let's figure out the real type and assign it to users

2022-10-19 21:24 UTC, yeezick commented on src/app/features/users/userSlice.tsx
> +  users: getOneUser(),
the type of return object may need to be extended from MongoDB types (if there is one)

2022-10-19 21:25 UTC, yeezick commented on src/app/features/users/userSlice.tsx
> +    getCurrentUser: (state, action: PayloadAction<any>) => {
let's see if we can find the type for the PayloadAction 
https://redux-toolkit.js.org/usage/usage-with-typescript

2022-10-19 21:36 UTC, yeezick commented on src/screens/Landing/Landing.tsx
> +    userLogged.then((res: any) => setCurrentUser(res));
give res the `UserInterface` type too

2022-10-19 21:40 UTC, yeezick commented on src/screens/Landing/Landing.tsx
> +    userLogged.then((res: any) => setCurrentUser(res));
this is where you would try to call `getAllUsers` and set the first one

2022-10-19 21:42 UTC, yeezick commented on src/screens/Landing/Landing.tsx
> +      {currentUser?.member_of_projects?.map((projects: any, id: number) => (
give projects the Project type

2022-10-19 21:47 UTC, yeezick requested changes
Everything looks very solid to me, just a few suggestions on types, sand another suggestion on how to fetch a single user for now 

I'd also like to suggest renaming app to utilities and throwing the api directory in there as well

You can also break up the User. & Project itnerface into their own files and then moving it to an "Interfaces" folder within utilities

2022-10-19 23:47 UTC, HectorIlarraza commented on src/api/users.js
> +  let testId = '634f0bfa570c7584a7c6a0e5';
done as per our PR video chat

2022-10-19 23:48 UTC, HectorIlarraza commented on src/app/features/users/userSlice.tsx
> +  users: getOneUser(),
Reformatted during PR call

2022-10-19 23:49 UTC, HectorIlarraza commented on src/app/features/users/userSlice.tsx
> +    getCurrentUser: (state, action: PayloadAction<any>) => {
Completed, we used the UserInterface as a type from interface

2022-10-19 23:51 UTC, HectorIlarraza commented on src/screens/Landing/Landing.tsx
> +    userLogged.then((res: any) => setCurrentUser(res));
Done completed remarks on retrieving the first user from gettingAllUser[0]

2022-10-19 23:52 UTC, HectorIlarraza commented on src/screens/Landing/Landing.tsx
> +      {currentUser?.member_of_projects?.map((projects: any, id: number) => (
Completed, added Project type as the project type

2022-10-20 23:33 UTC, yeezick commented on src/screens/Landing/Landing.tsx
> +    console.log(allUser);
remove console log

2022-10-20 23:33 UTC, yeezick commented on src/utilities/Interface/UserInterface.ts
> +export interface Project {
user and project should have their own interface files

2022-10-21 00:18 UTC, Bestnogm1 commented on src/screens/Landing/Landing.tsx
> +    console.log(allUser);
console.log was removed

2022-10-21 00:37 UTC, yeezick approved these changes

2022-10-21 00:54 UTC, yeezick approved these changes

2022-10-21 00:56 UTC, merged