Migrated BC-455-image-modal code into V2 and now reflects correct git…
yeezick/bootcampr pull request #52
Opened 2023-05-23 03:51 UTC by HectorIlarraza

… history and ready for final review... I hope lol

2023-06-08 21:15 UTC, gooliajulia commented on src/utils/api/services.js
> +// Modify verison for Blob handling, might not be needed
Is it safe to delete all of this commented out code? Or is there a reason you want to keep it?

2023-06-08 21:17 UTC, gooliajulia commented on src/utils/redux/slices/avatarSlice.ts
> +import { AvatarState } from '../../../interfaces/ProfileImageInterfaces'
can this be changed to an alias import?

2023-06-08 21:22 UTC, gooliajulia commented on src/components/Crop/Utils/CropImage.tsx
> +  console.log('canvasWithOrientation:', canvasWithOrientation)
remove console.log

2023-06-08 21:22 UTC, gooliajulia commented on src/components/Crop/Utils/CropImage.tsx
> +      console.log('Blob file:', file)
remove console.log

2023-06-08 21:22 UTC, gooliajulia commented on src/components/Crop/Utils/CropImage.tsx
> +        console.log('Blob URL:', blobUrl)
remove console.log

2023-06-08 21:24 UTC, gooliajulia commented on src/components/ImageEditorModal/ImageEditorControls.tsx
> +    console.log('Change Photo button clicked')
remove console.log

2023-06-08 21:27 UTC, gooliajulia commented on src/components/ImageEditorModal/ImageEditorModal.tsx
> +              console.log('Failed to generate cropped image URL:', error)
swap for console.error(...

2023-06-08 21:27 UTC, gooliajulia commented on src/components/ImageEditorModal/ImageEditorModal.tsx
> +          console.log('Cropped Image URL:', croppedImageURL) // Wrong URL
remove console.log

2023-06-08 21:27 UTC, gooliajulia commented on src/components/ImageEditorModal/ImageEditorModalUtils.ts
> +  console.log('Cropped Image Blob:', blob)
remove console.log

2023-06-08 21:39 UTC, gooliajulia commented on src/screens/Landing/Landing.tsx
> +      console.log('Unable to set random user:', err)
swap for console.error

2023-06-08 21:40 UTC, gooliajulia commented on src/screens/ProfilePreviewImage/ProfilePreviewImage.tsx
> +    console.log('Change Photo button clicked')
remove console.log

2023-06-08 21:40 UTC, gooliajulia commented on src/screens/ProfilePreviewImage/ProfilePreviewImage.tsx
> +    console.log('Uploaded image:', image)
remove console.log

2023-06-08 21:40 UTC, gooliajulia commented on src/screens/ProfilePreviewImage/ProfilePreviewImage.tsx
> +      .catch(err => console.log('Failed to update image:', err))
swap for console.error

2023-06-08 21:41 UTC, gooliajulia commented on src/screens/ProfilePreviewImage/ProfilePreviewImage.tsx
> +    console.log('Delete button clicked')
remove console.log

2023-06-08 21:44 UTC, gooliajulia commented on src/screens/ProfilePreviewImage/ProfilePreviewImage.tsx
> +      } else {
If code in a try block is unsuccessul, its best to "throw" an error that the catch block below can handle
`throw Error('Unsuccessful', res)`
and that will be the `err` object received in the catch blow
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw

2023-06-08 21:47 UTC, gooliajulia requested changes
Impressive stuff @HectorIlarraza ! 👏  Handful of comments, mostly removing console.logs and swapping in console.errors

Lmk when you address comments and I'll give it an approval

2023-06-09 03:57 UTC, HectorIlarraza commented on src/utils/api/services.js
> +// Modify verison for Blob handling, might not be needed
Yea it still might be needed in the future but i will save it on my notes to look back into

2023-06-09 04:04 UTC, HectorIlarraza commented on src/utils/redux/slices/avatarSlice.ts
> +import { AvatarState } from '../../../interfaces/ProfileImageInterfaces'
strange these should be removed since they are in my branch 🤔 ? After this next commit lets see if its still there

2023-06-09 04:04 UTC, HectorIlarraza commented on src/components/Crop/Utils/CropImage.tsx
> +  console.log('canvasWithOrientation:', canvasWithOrientation)
strange these should be removed since they are in my branch 🤔 ? After this next commit lets see if its still there

2023-06-09 04:37 UTC, HectorIlarraza commented on src/screens/ProfilePreviewImage/ProfilePreviewImage.tsx
> +      } else {
Oh wow, never used this before but after reading what u wrote and shared i will start implementing this in the future!

2023-06-09 04:53 UTC, HectorIlarraza commented on src/utils/redux/slices/avatarSlice.ts
> +import { AvatarState } from '../../../interfaces/ProfileImageInterfaces'
actually yes and done

2023-06-09 23:29 UTC, gooliajulia approved these changes

2023-06-09 23:30 UTC, merged