Feature/bc 475 view and edit profile component
yeezick/bootcampr pull request #54
Opened 2023-06-05 20:18 UTC by HectorIlarraza

2023-06-05 23:50 UTC, yeezick commented on src/interfaces/UserInterface.ts
> +    githubUrl: string
this should be optional as a UXD won't have this url

2023-06-05 23:53 UTC, yeezick commented on src/screens/Auth/RegisterUserInfo/RegisterUserInfo.tsx
> +    }
confused about this statement as we're checking a static array if it includes the name of the input then assigning it userForm.links 

while in the else statement we're skipping `.links` and setting the input name as `userForm[name]: value`

2023-06-05 23:55 UTC, yeezick commented on src/screens/UserProfile/EditProfile.scss
> +    p {
since all other classes branch off `&__` let's move the plain selectors above the class extensions

2023-06-05 23:57 UTC, yeezick commented on src/screens/UserProfile/EditProfile.tsx
> +    }
same comment as above

2023-06-06 00:00 UTC, yeezick commented on src/screens/UserProfile/UserProfile.tsx
> +  console.log(authUser)
remove log

2023-06-06 00:01 UTC, yeezick commented on src/screens/UserProfile/UserProfile.tsx
let's remove the conditionals that have dummy info
only a logged in user should be able to reach this page

2023-06-06 00:02 UTC, yeezick commented on src/screens/UserProfile/UserProfile.tsx
> +                <a
role should only check if the user is an SWE

2023-06-06 00:04 UTC, yeezick commented on src/utils/data/userConstants.ts
>        bio: '',
combine initial state and empty user so that initialState.auth.user = emptyUser

2023-06-06 00:05 UTC, yeezick commented on src/utils/redux/slices/userSlice.ts
> +        }
we shouldn't have to hardcode this if the user is submitting this info themselves from their form

2023-06-06 00:06 UTC, yeezick requested changes
good pr! questions/comments above

2023-06-06 00:17 UTC, yeezick commented on src/screens/UserProfile/UserProfile.tsx
> +              {authUser.firstName ? authUser.firstName : 'Jeanine'}{' '}
`authUser.firstName && <p> {authUser.firstName} </p>

2023-06-07 12:12 UTC, HectorIlarraza commented on src/screens/Auth/RegisterUserInfo/RegisterUserInfo.tsx
> +    }
I now know why i did it this way its because 

```
const {
    bio,
    firstName,
    lastName,
    links: { githubUrl, linkedinUrl, portfolioUrl },
    profilePicture,
    role,
    _id: userId,
  } = userForm```

has a nested object and in order to properly access it from the userForm i would need to look in it via the array. If it is, it means the changed field is one of the properties inside links, and so the value of this property is updated inside userForm.links.

if the name of the input field isn't found in the array, it means that the changed field is a top-level property in userForm (like firstName, lastName, or bio). which in terms updates the top-level property directly in userForm, without going through links.

Because userForm includes nested objects, the function needs to differentiate between changes to top-level properties versus nested properties. By doing so, it ensures that all properties, whether top-level or nested, are accurately tracked and updated in response to user input.

I did update the function to make it easier and cleaner to read so let me know if you like the updated one better or if u don't like this approach. We can flatten the object but that would require changing the interface and backend as well.

2023-06-07 17:02 UTC, yeezick commented on src/screens/Auth/RegisterUserInfo/RegisterUserInfo.tsx
> +    }
i see, thanks for explaining it to me!
rather than hardcoding a array, let's try 
```
    if (Object.keys(userform.links).includes(name)) {
      setUserForm({
        ...userForm,
        links: {
          ...userForm.links,
          [name]: value,
        },
      })
    }
``` 
so that it's dynamic to whatever links the user adds and only checks the links they do have

2023-06-07 17:06 UTC, yeezick commented on src/screens/Auth/RegisterUserInfo/RegisterUserInfo.tsx
> +  const nestedProperties = Object.keys(userForm.links)
disregard other comment as u already handled it here! 
inly suggestion is to rename var to nestedlinks as its more semantic

2023-06-07 17:07 UTC, yeezick commented on src/screens/Auth/RegisterUserInfo/RegisterUserInfo.tsx
> +    }
sounds good to me! thanks for explaining

2023-06-07 17:18 UTC, yeezick submitted a review, later dismissed

2023-06-07 22:30 UTC, yeezick approved these changes

2023-06-07 22:30 UTC, merged