Feature/bc 462 sync chat with figma
yeezick/bootcampr pull request #55
Opened 2023-06-05 22:46 UTC by jasonmar08

2023-06-07 20:00 UTC, HectorIlarraza requested changes
Overall a great job Jason! you have evolved and stepped up ur coding game to a new level, I learned so much reviewing ur PR. There are some minor areas that need to be changed and suggestions I made for your code that I hope makes it more fluid and easier to read. Please let me know if they are helpful after giving them some thought.

2023-06-13 20:07 UTC, HectorIlarraza reviewed
Terrific work Jason just some questions that would help me understand if the methods suggested helped in any way. Once you answer them ill approve ASAP!

2023-06-13 20:53 UTC, jasonmar08 commented on src/components/ChatDialog/ChatDialogMain/ChatDialogMain.tsx
> +  const titleContentLookup = {
Yeah, first time I used a lookup table and I like it. If the occasion allows for it, I think it's a great option and it avoids the sequential evaluation that if-else statements and switch statements encompass.

2023-06-13 20:53 UTC, jasonmar08 commented on src/interfaces/ChatInterface.ts
> +export interface ChatSliceInterface {
I already had the interface set up in the userSlice and transferred it to a chatSlice. I think it separates the logic for chat from authUser, making the code more organized and maintanable.

2023-06-13 20:53 UTC, jasonmar08 commented on src/utils/data/chatConstants.ts
> +import {
Yes, the constants helped! I like how organized they are now, and it also makes it easier if another developer were to work on the chat. If you type `ChatScreen.`, a list of all the chatScreens appears so you can select your desired one.

2023-06-13 20:53 UTC, jasonmar08 commented on src/utils/redux/slices/chatSlice.ts
> +import { PayloadAction, createSlice } from '@reduxjs/toolkit'
I think separating the chatSlice makes it more organized and maintainable.

2023-06-13 20:55 UTC, HectorIlarraza approved these changes

2023-06-13 20:57 UTC, merged