Feature/bc 323 sign in functionality
yeezick/bootcampr pull request #6
Opened 2022-10-19 23:57 UTC by zendrias

- Created login screen.
- Check username and password fields before submit button is enabled.
- Handle 201 HTTP response as well as 401 response gracefully. ( Code 401 API response was throwing Axios error )
- Rendering user/unauthenticated-user JSON to the screen.
- Remove the token from local storage if the user submits invalid credentials while logged in.

2022-10-25 01:01 UTC, yeezick commented on src/api/apiConfig.js
> +});
curious about what this does

2022-10-25 01:04 UTC, yeezick commented on src/api/users.js
> +    }
this too, how did the user receive unauthorized but had a token?
it should never be the case anyway, we haven't blocked that user flow yet but a user should never a see a sign-in page if they're already logged in

2022-10-25 01:05 UTC, yeezick commented on src/screens/SignIn/SignIn.tsx
> +  );
would love to hear about why you chose refs over inputs & state, i've never seen this method for forms before

2022-10-25 01:08 UTC, yeezick commented on src/screens/SignIn/SignIn.tsx
> +
please add labels & style forms with flex columns for readability

2022-10-25 01:10 UTC, yeezick requested changes
just a few questions and a suggestion

the api also fails with:
`"Cannot read properties of null (reading '_doc')"`
if you made changes to the backend, there's no pr for it 

now that Koffi has integrated the redux store, this would be good to merge with development and store the authenticated user in redux. you can also route the user to `/users/:id`, I should be done with UserProfile by the time this gets merged

2022-10-26 20:59 UTC, zendrias commented on src/api/apiConfig.js
> +});
From what I've seen so far using Axios, if Axios gets an HTTP response code, other than 200 - 299, it is automatically classified as an error. So the 401 response was throwing an error.  so I'm catching the "error", and returning just the unauthorized message here.  That's what worked out for me.

2022-10-26 21:00 UTC, zendrias commented on src/api/users.js
> +    }
I thought I might as well add it in case, but touche.

2022-10-26 21:07 UTC, zendrias commented on src/screens/SignIn/SignIn.tsx
> +  );
I think it looks cleaner, I got to use a less common hook, and I saw no reason for needing state. I'm open to new ideas though!

2022-10-29 23:13 UTC, yeezick commented
@zendrias so I looked deeper into refs vs. state, mainly [this article](https://css-tricks.com/react-forms-using-refs/) and while interesting, i don't think this would be the right use case for refs. Similarly, this would be the only form using refs or state in the app and it might be better to stick to one method until we have a reason to use an alternative.
I admire the initiative though! Made me want to look deeper into refs.

Once you've handled a conversation above, resolve them so i know they're taken care of.

2022-11-09 02:23 UTC, yeezick commented on src/layout/Nav/Nav.tsx
> +  console.log(authUser)
remove console log

2022-11-09 02:23 UTC, yeezick commented on src/screens/SignIn/SignIn.module.css
> +
whitespace

2022-11-09 02:23 UTC, yeezick commented on src/screens/SignIn/SignIn.module.css
> +  margin: 0;
is this necessary? i saw you applied to index.scss as well, doesn't that apply to all children of the index.ts file?

2022-11-09 02:24 UTC, yeezick commented on src/screens/SignIn/SignIn.module.css
> +  width: 40vmin;
please alphabetize

2022-11-09 02:25 UTC, yeezick commented on src/screens/SignIn/SignIn.tsx
> +interface FormData {
move this to `/utilities/types/UserInterface` and rename to something more semantic like `SignInInterface`

2022-11-09 02:26 UTC, yeezick commented on src/screens/SignIn/SignIn.tsx
> +    else setButtonDisabled(true)
this is cool never seen an if...else like this

2022-11-09 02:36 UTC, yeezick commented on src/screens/SignIn/SignIn.tsx
> +    if (response?.message === "Invalid email or password" ?? false) return setInvalidCredentials(true)
never seen ?? before so i looked into this too. accorting to [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) we're not using it properly as the left conditional would return either true or false, never null or undefined. it might be null or undefined if response comes back like that from the API which we'd have to clean up in an error handling epic. 

the conditional itself is also slightly hard to follow
`if ((response exists and has a message that equals 'invalid...' ) <= doesn't return 'null' or 'undefined' then return false) => return invalidCredentials(true)`

i'd suggest breaking this up a bit more to be easier to read. i trust you that it works and it was clever, but always prefer legibility over cleverness (unless youre a competitive programmer)

2022-11-09 02:37 UTC, yeezick commented on src/screens/SignIn/SignIn.tsx
> +          <div className={styles.flex_column}>
add a line break between input-divs, makes them easier to read

2022-11-09 02:38 UTC, yeezick commented on src/screens/SignIn/SignIn.tsx
> +      <p className={`${!invalidCredentials ? styles.hidden : styles.error_message}`}>{invalidCredentials && <span>Invalid Credentials</span>}</p>
this is also very tricky. consider turning this into a component that receives props to decide on what to render.

and rather than set the styles to hidden, we should unmount/not return this component at all instead

2022-11-09 02:39 UTC, yeezick commented on src/utilities/api/apiConfig.js
> +
whitespace

2022-11-09 02:41 UTC, yeezick commented on src/utilities/api/apiConfig.js
> +
i'm curious what the interceptor below does too

2022-11-09 02:41 UTC, yeezick commented on src/index.css
> +
whitespace

2022-11-09 02:41 UTC, yeezick requested changes
few more things

2022-11-14 00:34 UTC, zendrias commented on src/screens/SignIn/SignIn.module.css
> +  margin: 0;
Yeah, I forgot I put one in the index.css.  I have always been a fan of CSS resets but it's but for debate. I'll remove the one I put in. Check Out [This Article](https://www.webfx.com/blog/web-design/should-you-reset-your-css/)

2022-11-14 01:18 UTC, zendrias commented on src/utilities/api/apiConfig.js
> +
Axios considers any API status response other than a 201 to be an error. So I'm just intercepting the error, and simply returning the error message.

2022-11-26 18:51 UTC, yeezick commented
I removed a console log and merged with develop, this is approved!

2022-11-26 18:51 UTC, yeezick approved these changes

2022-12-02 14:03 UTC, merged