created a reusable snackbar class to be able to be used any where in …
yeezick/bootcampr pull request #67
Opened 2023-07-20 22:10 UTC by Bestnogm1

created the snack bar to be used as a reusable component `  isOpen?: boolean
  message?: string
  duration?: number
  vertical?: 'top' | 'bottom'   // default: bottom
  horizontal?: 'left' | 'center' | 'right'  // default: left
  snackbarStyle?: string 
}`  these are some of the properties that someone needs to input when passing in as props  to the <SnackBarToastProps/> component

2023-08-06 20:11 UTC, yeezick commented on src/components/SnackBarToast/SnackBarToast.tsx
> +import WarningAmberIcon from '@mui/icons-material/WarningAmber'
consolidate imports with 
`import {checkIcon, ErrorOutlineIcon, WarningAmberIcon} from '@mui/icons-material'`

2023-08-06 20:12 UTC, yeezick commented on src/components/SnackBarToast/SnackBarToast.tsx
> +}
move interface to interfaces directory

2023-08-06 20:13 UTC, yeezick commented on src/components/Kanban/AllTickets.tsx
> +  })
the ability to open snack bars and populate with information should be available from any place in the app so it's probably best to set this up in redux so that we can call on the snackbar anywhere

2023-08-06 20:18 UTC, yeezick requested changes
great work! you made the implementation look super simple

before we merge we should move the ability to open & populate snackbars to redux so that we can use the same component for other actions like successfully creating calendar events or error toasts when an api call fails 

i know it wasn't in the scope of the ticket but could you add a button to the sidemenu that onClick will trigger a snackbar with any message you want (like a joke or inspo message)?

2023-08-09 21:48 UTC, Bestnogm1 commented on src/components/SnackBarToast/SnackBarToast.tsx
> +import WarningAmberIcon from '@mui/icons-material/WarningAmber'
tried this and its just not working

2023-08-10 17:32 UTC, yeezick approved these changes

2023-08-14 23:18 UTC, merged