Feature/bc 485 meeting modal v2
yeezick/bootcampr pull request #71
Opened 2023-08-06 21:39 UTC by yeezick

This PR accomplishes [BC-538: Cont - Finish & design meeting modal](https://bootcamper.atlassian.net/browse/BC-538?atlOrigin=eyJpIjoiOWYyOGY1MGM1YmE2NGIyZDgwZjZiM2NkYmE1NWEwN2MiLCJwIjoiaiJ9) with the ability to create events that send out calendar invites to users as well as instantly render on the calendar.

2023-08-06 21:42 UTC, yeezick commented on src/components/Calendar/MeetingModal/MeetingModal.tsx
> +          <div style={{ marginTop: '20px' }}>
use a class name instead of inline style

2023-08-06 21:42 UTC, yeezick commented on src/components/Calendar/MeetingModal/MeetingModal.tsx
> +              {/* </div> */}
dead code

2023-08-06 21:45 UTC, yeezick commented on src/utils/api/projects.js
> +export const getProjectMembers = async projectId => {
is this needed? get project members should be in redux

2023-08-11 22:39 UTC, HectorIlarraza requested changes
Great Work as always Eric, I always learn something new reviewing ur PRs!

I left several comments that are mostly quick fixes and questions for my own sanity/curiosity. Once addressed we can merge this bad boi ASAP!

2023-08-11 22:39 UTC, HectorIlarraza commented on src/components/Calendar/MeetingModal/SelectAttendees.tsx
> +          <FormGroup>
This file is great nothing wrong with it, but after reviewing PRs for a while now and seeing many types of coding methods and comparing them to my method, I seem to notice that when it comes to rendering instances like the FormGroup that we sometimes either leave it like that in the JSX or we create a separate function to house it instead which makes it more readable. But we aren't always consistent with doing it that way for every file that might have something similar. Should this be looked into to have the team adopt a practice to create separate functions to handle instances like FormGroup for enhance readability or leave it as is I'm just overthinking it?

2023-08-11 22:39 UTC, HectorIlarraza commented on src/components/Calendar/MeetingModal/SelectTime.tsx
> +  // update available options for end type to be next option after start time
Looks like its doing what u wrote so it can be removed now correct?

2023-08-11 22:39 UTC, HectorIlarraza commented on src/components/Calendar/MeetingModal/SelectTimeZone.tsx
> +  return (
SX here as well

2023-08-11 22:39 UTC, HectorIlarraza commented on src/components/Calendar/MeetingModal/SelectTime.tsx
> +  return (
Sx here as well

2023-08-11 22:39 UTC, HectorIlarraza commented on src/utils/helpers/calendarHelpers.ts
> +  // Adjust for AM/PM period
This is being accomplished so it can be removed, correct?

2023-08-11 22:39 UTC, HectorIlarraza commented on src/utils/helpers/calendarHelpers.ts
> +export const combineDateWithTime = (date, selectedTime) => {
Overall Great file, but maybe consider adding introductory comments at the beginning of the module as we did in the past (EX: 
/**
 * ProfilePreviewImage component displays a preview of the profile image, allowing the user to add, edit, or delete the image.
 * @param {boolean} open - Indicates if the dialog is open.
 * @param {Function} onClose - Function to call when the dialog is closed.
 * @param {string} uploadedImage - The uploaded image in base64 format.
 * @returns {JSX.Element} - ProfilePreviewImage component.
 */) to provide a high-level overview of its purpose and the functions it contains, cause I had to sit and decipher this var by var lol.

2023-08-13 23:41 UTC, yeezick commented on src/components/Calendar/MeetingModal/DateFields.tsx
> +  const handleDate = newDate =>
i think this name is fine for now, the only alternative is `DateAndTimeFields` which feels like a bit much given this component is unique to the meeting modal right now

2023-08-13 23:46 UTC, yeezick commented on src/components/Calendar/MeetingModal/SelectTime.tsx
> +  // update available options for end type to be next option after start time
this was a context comment to let others know what that useEffect is doing, i've elaborated on it to make it more clear

2023-08-14 22:40 UTC, yeezick commented on src/components/Calendar/MeetingModal/MeetingModal.tsx
> +        if (inviteAll === false) {
the simplest way i can make it is 
``` 
      projectMembers.forEach(
        // inviteAll is the current state
        member => (updatedAttendance[member.email] = inviteAll === false)
      )
```
but is it worth it at the cost of legibility or did u have another suggestion

2023-08-14 22:51 UTC, yeezick commented on src/components/Calendar/MeetingModal/MeetingModal.tsx
> +              onChange={e => handleFormInputChange(e, setMeetingText)}
i debated this too since we need the e event but also the second arg and only alternative is to create the function in the file using a callback but thats seemed over abstract for a one liner

still haven't concluded which is cleaner tho

2023-08-14 23:12 UTC, yeezick commented
I fixed all your suggestions except the styling ones if it broke the styling. Iffy about inline styling also but MUI doesn't port over the styles 1:1 via classes. Nice to have for now though I agree it'd be better to stick to 1 practice. 
Those classes were turned in objects to move lessen the line count in the JSX

2023-08-14 23:13 UTC, yeezick commented on src/components/Calendar/CalendarTabs.tsx
> +      component: <CalendarView events={events} setEvents={setEvents} />,
this should be a discussion

2023-08-15 02:16 UTC, HectorIlarraza commented on src/components/Calendar/MeetingModal/MeetingModal.tsx
> +        if (inviteAll === false) {
My mad I didn't clarify this better I meant instead of checking if (inviteAll === false), you could directly toggle the opposite value with !inviteAll.

2023-08-15 02:16 UTC, HectorIlarraza commented on src/components/Calendar/MeetingModal/SelectTime.tsx
> +  // update available options for end type to be next option after start time
Ahhhh ok, I didn't know that, should we include some code nickname to adopt to let others know of context comments though out the files for example `// CONTEXT: update available options for end type to be next option after start time` similar to our TODO's comments?

2023-08-15 21:57 UTC, yeezick commented on src/components/Calendar/MeetingModal/MeetingModal.tsx
> +        if (inviteAll === false) {
that works

2023-08-15 22:06 UTC, yeezick commented on src/components/Calendar/MeetingModal/SelectAttendees.tsx
> +          <FormGroup>
This should be a discussion too

2023-08-16 00:15 UTC, HectorIlarraza approved these changes

2023-08-16 01:45 UTC, merged