Bc 315 navbar
yeezick/bootcampr pull request #73
Opened 2023-08-14 02:23 UTC by mendo94

As a user, I want to be able to navigate to the following pages:

landing/home page (bc icon)

project portal

how bc works

about us

As well as being able to:

open the chat dialog 

open the account dropdown

From anywhere on the site so that I can easily access these features and pages. 

AC’s
Update nav links to reflect those mentioned above & still in figma 

Design nav to be like the figma 

![Screen Shot 2023-08-13 at 10 22 49 PM](https://github.com/yeezick/bootcampr/assets/94413237/a3c050c5-6b5d-413e-b9d0-2df909006861)

2023-08-14 23:25 UTC, yeezick commented on src/layout/Nav/Nav.tsx
> +            onClick={() => toggleChatBox()}
suggestion to turn this into a [named function vs anon callback ](https://www.geeksforgeeks.org/difference-between-anonymous-and-named-functions-in-javascript/#)

2023-08-14 23:26 UTC, yeezick commented on src/layout/Nav/Nav.scss
> +    background: var(--white-ffffff, #fefefe);
wondering about these vars, why do we have to declare the hex code and a var name?

2023-08-14 23:28 UTC, yeezick commented on src/App.tsx
> +import ProjectPortal from 'layout/Nav/Links/ProjectPortal'
We should create the AboutUs and HowTo screens in the screens/landing directory

Project portal is unique and not an actual page but more of a portal to the project features when a user is logged in

For example, there is no sidebar in the landing, about, or how to screens but when the user clicks "project portal" they are routed to the project details screen with the sidebar always open.

2023-08-14 23:29 UTC, yeezick commented on src/App.tsx
> +import ProjectPortal from 'layout/Nav/Links/ProjectPortal'
and they should be exported as consts, not default exports

2023-08-14 23:29 UTC, yeezick requested changes
only one worth waiting for is the comment about screens and project portal

2023-08-15 00:01 UTC, mendo94 commented on src/App.tsx
> +import ProjectPortal from 'layout/Nav/Links/ProjectPortal'
Okay agree about the project portal, the screens I am not following the example you provided. Send help

2023-08-21 01:36 UTC, mendo94 commented on src/layout/Nav/Nav.tsx
> +            onClick={() => toggleChatBox()}
moved to a named function

2023-08-21 01:37 UTC, mendo94 commented on src/layout/Nav/Nav.scss
> +    background: var(--white-ffffff, #fefefe);
you never know if you need a backup to your backup color, jk I copied the style straight from Figma. Removed vars.

2023-08-21 01:38 UTC, mendo94 commented on src/App.tsx
> +import ProjectPortal from 'layout/Nav/Links/ProjectPortal'
moved to the Landing directory, moved project portal to redux project slice, exported as consts

2023-08-27 01:51 UTC, yeezick approved these changes

2023-08-27 01:51 UTC, merged