Feature/bc 558 set up profile
yeezick/bootcampr pull request #79
Opened 2023-09-01 01:34 UTC by HectorIlarraza

### Feature: Add SetUp Profile feature on Onboarding Flow:

This pull request addresses Jira ticket [BC-558 ], which aims to enhance the user experience by allowing users in the onboarding flow to seamlessly navigate from the Availability screen to the Setup Profile screen. Additionally, this pull request ensures that the Setup Profile component shares the same structure as the Edit Profile component. The implementation adheres to the Figma design for consistent styling.

### Changes Made:

- Implemented the necessary logic to enable navigation from the Availability screen to the Setup Profile screen upon clicking the Submit button.
- Created a shared component structure between the Setup Profile and Edit Profile components to ensure code reusability and maintainability.
- Styled the Setup Profile component to match the design specifications outlined in Figma.
- Incorporated the functionality to save user information entered in the Setup Profile screen to the database when the Save button is clicked.

### Acceptance Criteria:

- Clicking the Submit button on the Availability screen seamlessly navigates the user to the Setup Profile screen.
- The Setup Profile component mirrors the structure of the Edit Profile component.
- The styling of the Setup Profile component matches the design outlined in Figma.
- Saving user information in the Setup Profile screen updates the corresponding user data in the database.

### Related Issue:

[Link to Jira Ticket](https://bootcamper.atlassian.net/browse/BC-558)
[Link to Figma File](https://www.figma.com/file/0MxlQWeXfGPjwUrwWjwgk2/bootcamper---lofi-proto?type=design&node-id=7188-14959&mode=dev)

### Reviewer Notes:

When submitting the setup Profile button it causes the user to log off while still navigating to the final paginator page, this could be because the component needs to be adjusted, I can create a ticket for that or add to this one via a new commit. 

### Deployment Notes:

No special deployment requirements or changes are needed.

**_Please review and provide feedback as needed. Thank you!_**

2023-09-02 02:45 UTC, yeezick requested changes
minor updates here and questions
main things to call out (please follow up in a team meeting) 
* BEM practice
* using MUI for inputs and labels across the app (this might be able to slide for now but will eventually need a ticket to refactor the inputs in this PR to custom input components we'll create through MUI

2023-09-02 02:45 UTC, yeezick commented on src/screens/Onboarding/OnboardingSetUpProfile.tsx
> +                // disabled={}
comment

2023-09-02 02:45 UTC, yeezick commented on src/screens/Onboarding/OnboardingSetUpProfile.tsx
> +                <FiArrowLeft className='setupProfile__profile-arrow-l' />
i'm also seeing alot of BEM but we haven't discussed this with the team yet.. so your files will be different from the css implementation in the rest of the app

2023-09-02 02:45 UTC, yeezick commented on src/screens/UserProfile/UserProfile.tsx
> +            authUser?.role === 'UX Designer') && <p>{authUser?.bio}</p>}
a user needs these fields to register their account so these fields should always exist.
if it's breaking because on the first render that information has not been pulled from state yet then we should just return null for this component until it rerenders with the right info.

2023-09-02 02:45 UTC, yeezick commented on src/screens/UserProfile/UserProfile.tsx
> +                authUser?.role === 'UX Designer') &&
i see this check a lot to see if the user has a role. this should be converted to a function or variable since it's repeated 3x times

2023-09-02 19:18 UTC, HectorIlarraza commented on src/screens/UserProfile/UserProfile.tsx
> +            authUser?.role === 'UX Designer') && <p>{authUser?.bio}</p>}
This was my mistake, I meant to revert these back since Koffi and Lauren were helping me spot the issue of why the Role wasn't updating after finishing the onboarding flow.

2023-09-02 19:18 UTC, HectorIlarraza commented on src/screens/UserProfile/UserProfile.tsx
> +                authUser?.role === 'UX Designer') &&
done

2023-09-04 07:02 UTC, yeezick commented on src/interfaces/UserInterface.ts
> +  email?: string
yeah it would either be that or creating a new interface that omits the email property but don't want to make it optional for the core user interface 
example of omitting a property when assigning an interface 
`const User: Omit<UserInterface, "email">` 
https://www.typescriptlang.org/docs/handbook/utility-types.html#omittype-keys

2023-09-04 07:02 UTC, yeezick commented on src/screens/Onboarding/Onboarding.scss
> +  .onboarding-pag-container {
the type here is "page"

2023-09-04 07:03 UTC, yeezick commented on src/screens/Onboarding/OnboardingSetUpProfile.tsx
> +                <FiArrowLeft className='setupProfile__profile-arrow-l' />
yes please

2023-09-04 07:03 UTC, yeezick commented on src/screens/Onboarding/OnboardingSetUpProfile.tsx
> +                // disabled={}
was this removed?

2023-09-04 07:04 UTC, yeezick commented on src/screens/UserProfile/UserProfile.tsx
> +            authUser?.role === 'UX Designer') && <p>{authUser?.bio}</p>}
not sure if you fixed this already but not seeing authUser's role as existing

2023-09-04 07:05 UTC, yeezick commented on src/screens/UserProfile/UserProfile.tsx
> +                authUser?.role === 'UX Designer') &&
yeah i feel like you did do it but for some reason i don't have the latest changes on github, is everything pushed up?

2023-09-04 07:06 UTC, yeezick approved these changes
looks good!

2023-09-04 07:59 UTC, merged

2023-09-04 18:05 UTC, HectorIlarraza commented on src/interfaces/UserInterface.ts
> +  email?: string
Oh cool ill use this method for any future tickets, thanks for sharing

2023-09-04 18:07 UTC, HectorIlarraza commented on src/screens/Onboarding/OnboardingSetUpProfile.tsx
> +                // disabled={}
yea i did, isnt in my branch i pushed...strange that this still shows hmm

2023-09-04 18:12 UTC, HectorIlarraza commented on src/screens/UserProfile/UserProfile.tsx
> +            authUser?.role === 'UX Designer') && <p>{authUser?.bio}</p>}
i noticed when u look at the comments in GitHub comments section the changes don't reflect new commits on her especially when u click on the file link thru here, but when u go to the actual closed PR and check the files changed u see the latest changes i made.

2023-09-05 21:53 UTC, HectorIlarraza commented on src/screens/Onboarding/Onboarding.scss
> +  .onboarding-pag-container {
oh that was intentional, i'm reflecting pag for paginator but it can be changed to page if that's preferred