Feature/bc 328 edit a project
yeezick/bootcampr pull request #8
Opened 2022-10-23 19:08 UTC by aryannaf

- populates fields based on selected project to be edited
- change information and update project
Functionality complete, pending final tests after schema to be updated with IDs so projects can be accessed

2022-10-25 01:20 UTC, yeezick commented on src/App.tsx
> +          <Route path="/projects/:id" element={<EditProject />} />
use this route for the project's detail page, use `/projects/:id/edit` for their edit screen

2022-10-25 01:21 UTC, yeezick commented on src/layout/Nav/Nav.tsx
> +          <Link to="/projects/:id">Edit Project</Link>
this link needs a hardcoded id to work, the edit form renders but the alert says there's no project found & the url ends in `/:id`

to get a generic id, you can call `getAllProjects` then use the id for the first project in that array

2022-10-25 01:22 UTC, yeezick commented on src/screens/EditProject/EditProject.scss
> +}
loving the alphabetized css

2022-10-25 01:28 UTC, yeezick commented on src/screens/EditProject/EditProject.tsx
> +  }
- curious about the type for roles.. does the object-like types within the `[ ]` define the types for each element within the "roles" array? 
- Koffi's merge into development has a project interface in `/src/utilities/interfaces/` that you replace with this type. look into [rina's PR](https://github.com/yeezick/bootcampr/pull/7/files#diff-7d32dddd29025e3430b288c438b146868131585dc989e47705ec6c220c8d965b) and see if you can merge your types together. the type for a "role" may have to become its own interface as well

2022-10-25 01:46 UTC, yeezick commented on src/screens/EditProject/EditProject.tsx
> +    const [fileSelected, setFileSelected] = useState<File>();
actually super confused as to how the form values are being updated when the handler updates `setupdatedProject` but not the input values are set to `currentProject`

either way i think we can consolidate these states and set their types to the `EditProject` interface

2022-10-25 01:48 UTC, yeezick requested changes
minor suggestions, i also see that the edit project form is very similar to [this pr](https://github.com/yeezick/bootcampr/pull/4/files#diff-f0e7b21f6031669de938397b19803a3ed7b6dc5f44ef0785e8dfadc7a180f835) so if any of those conversations on the `CreateProject` screen can be applied here please do so

2022-11-20 16:29 UTC, mendo94 commented on src/App.tsx
> +          <Route path="/projects/:id" element={<EditProject />} />
changed path on app.tsx

2022-11-20 16:30 UTC, mendo94 commented on src/layout/Nav/Nav.tsx
> +          <Link to="/projects/:id">Edit Project</Link>
no longer necessary because redux store is now set up

2022-11-20 16:30 UTC, mendo94 commented on src/screens/EditProject/EditProject.tsx
> +  }
no longer setting props here and using the project interface instead

2022-11-20 16:31 UTC, mendo94 commented on src/screens/EditProject/EditProject.scss
> +}
thank you

2022-11-20 16:32 UTC, mendo94 commented on src/screens/EditProject/EditProject.tsx
> +    const [fileSelected, setFileSelected] = useState<File>();
values are set to current project now

2022-11-20 19:25 UTC, HectorIlarraza submitted a review, later dismissed
Perfect in my eyes Rina, I see no need to alter anything on ur PR

2022-11-20 19:25 UTC, HectorIlarraza commented on src/screens/CreateProject/EditProject.tsx
> +  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
40-68 learned a lot from this and its very cool, nothing to say just admiration

2022-11-20 23:07 UTC, mendo94 commented on src/screens/CreateProject/EditProject.tsx
> +  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
wow thanks for your review!

2022-11-27 00:01 UTC, yeezick submitted a review, later dismissed
Excellent work @mendo94, well-written and concise. Great reviews @HectorIlarraza! That's the kind of eye it takes to maintain quality!

2022-11-27 18:27 UTC, yeezick approved these changes

2022-11-27 18:28 UTC, merged