Feature/bc 528 edit meetins
yeezick/bootcampr pull request #80
Opened 2023-09-04 07:17 UTC by yeezick

This PR accomplishes [BC-528: allow user to update meeting information](https://bootcamper.atlassian.net/browse/BC-528?atlOrigin=eyJpIjoiMGY1M2M3NzQ4MzRkNGY1YTk1OWM5ZTc3N2FlZTdiZjMiLCJwIjoiaiJ9)
Primary changes: 
* Refactors modal state to live in redux in stead of locally so that edit/create/display modals leverage the same info object and toggler 
  * All state relies on ISO strings instead of dayjs objects now
* Enables users to click an event, view their, click to edit, submit their edits, and rehydrate the calendar
* Refactors modal and members to include an email map to avoid unnecessary object duplication while making it simple & performant to look up events & project members in their native arrays
* Also includes a skeleton for the ability to add google meets event so video chat is bulit in
* Provides basic styling for the display modal 

Todo: 
* TimeZone needs to be looked at deeper to be understood how the events translate for other members. The objects don't seem to be properly converted when a new timezone is selected. 
* FullCalendar reformats event ISO times to UTC, this required the gDateFields to work around this

2023-09-05 22:21 UTC, HectorIlarraza requested changes
Overall dope PR I just have some questions and quick fixes recommendations so we can merge this hefty file

2023-09-05 22:21 UTC, HectorIlarraza commented on src/utils/redux/slices/projectSlice.ts
> +// import { mapMembersByEmail } from 'utils/helpers'
comment?

2023-09-05 22:21 UTC, HectorIlarraza commented on src/utils/redux/slices/projectSlice.ts
> +      const updatedProject = produce(action.payload, draft => {
nice immer produce in use...taking notes ✏️ 📓

2023-09-05 22:21 UTC, HectorIlarraza commented on src/utils/redux/slices/projectSlice.ts
> +// TODO: moving this function to calendarHelpers breaks the app, need to look into why
Interesting so only when its inside the file itself it wont break and exporting it does hmmm could it be circular dependencies?

2023-09-06 00:25 UTC, yeezick commented on src/components/Calendar/CalendarHeader.tsx
> +  const dispatch = useAppDispatch()
you can ask @jasonmar08 why but he said we should be exclusively using `useAppDispatch`
if i said otherwise or you see the other implementation in code then we should be replacing those

2023-09-06 00:28 UTC, yeezick commented on src/components/Calendar/MeetingModal/DateFields.tsx
>    const handleDate = newDate =>
hmm.... i could see that argument but we can let it slide here. Immer would be best used in a case like:
```
const updatedObj = {
  ...originalObj, 
  user: {
    ...originalObj.user,
    links: {
      ...originalObj.user.links,
      github: 'github.com',
      }
    }
  }
```

we could get away with 1 nested spread but no more than that, immer should handle anything deeper than 1 level

2023-09-06 00:29 UTC, yeezick commented on src/components/Calendar/MeetingModal/DisplayAttendees.tsx
> +    <div className='invited-members'>
correct! since the `<div>` in the component below would be the first to render

2023-09-06 00:33 UTC, yeezick commented on src/components/Calendar/MeetingModal/DisplayMeetingModalStyles.scss
> +  display: grid;
XD 
this was the only use case that made sense/was easiest
big feeling im gonna regret this later but that's later's problem 😅

2023-09-06 00:34 UTC, yeezick commented on src/components/Calendar/MeetingModal/MeetingModal.tsx
> +export const MeetingModal = () => {
bro shut up or i'll kiss u

2023-09-06 00:34 UTC, yeezick commented on src/components/Calendar/MeetingModal/MeetingModal.tsx
> +export const MeetingModal = () => {
this made me blush

2023-09-06 00:35 UTC, yeezick commented on src/components/Calendar/MeetingModal/MeetingModal.tsx
> +            {/* TODO: Come back and replace with arrow  */}
delete this comment, resolved above

2023-09-06 00:38 UTC, yeezick commented on src/utils/redux/slices/projectSlice.ts
> +// TODO: moving this function to calendarHelpers breaks the app, need to look into why
yes!! 

I believe this file is being compiled before it gets to the utils directory, not sure how to resolve as I literally had to google circular dependencies

If we can set it up so those utils are being compiled first then that should resolve this error

2023-09-06 00:47 UTC, HectorIlarraza commented on src/components/Calendar/CalendarHeader.tsx
> +  const dispatch = useAppDispatch()
EEEK 😨  got to check the files i worked on and make those changes

2023-09-06 00:48 UTC, HectorIlarraza commented on src/components/Calendar/MeetingModal/DateFields.tsx
>    const handleDate = newDate =>
I see 🤔, thank you for the insight ✏️ 📓

2023-09-06 00:49 UTC, HectorIlarraza commented on src/components/Calendar/MeetingModal/DisplayAttendees.tsx
> +    <div className='invited-members'>
That's a neat trick, I need to try this out one day

2023-09-06 00:50 UTC, HectorIlarraza commented on src/components/Calendar/MeetingModal/DisplayMeetingModalStyles.scss
> +  display: grid;
Lol I really hope u don't have to but if u do.... well.... lol u understand

2023-09-06 00:51 UTC, HectorIlarraza commented on src/components/Calendar/MeetingModal/MeetingModal.tsx
> +export const MeetingModal = () => {
lol pucker them suckers up

2023-09-06 00:53 UTC, HectorIlarraza commented on src/utils/redux/slices/projectSlice.ts
> +// TODO: moving this function to calendarHelpers breaks the app, need to look into why
yea makes sense, i had to look into this as well when i read the note, definitely looking forward to ur fix for this.

2023-09-06 00:55 UTC, HectorIlarraza approved these changes
Clean and approved

2023-09-06 22:56 UTC, merged