BC-603-edit-user-profile-crashes
yeezick/bootcampr pull request #84
Opened 2023-09-15 03:06 UTC by HectorIlarraza

### Feature: Edit User Profile Stability Improvements

This Jira ticket, labeled "Edit User Profile Crashes," aimed to address and enhance the stability of the user profile editing process. The changes made and their alignment with the acceptance criteria are summarized below:

### Changes Made:

Stability Enhancements: Implemented improvements to ensure that editing the user profile does not result in crashes or unexpected errors. This involved identifying and addressing potential issues that could lead to instability.

User Session Preservation: Requires refactoring randomUserLogin logic with auth capabilities.

Profile Data Saving: Implemented functionality to save user profile updates securely. When a user makes edits to their profile and clicks "Save," the changes are properly saved (Minus Profile Picture, my other ticket will contain the update fix for that).

### Acceptance Criteria:

**AC01: Ensure Editing User Profile does not crash**

- Given: The user is on the "My Profile" page.
- When: The user clicks on "Edit My Profile."
- Then: The page should not crash.

**AC02: Ensure Editing User Profile does not log the user out**

- Given: The user is on the "My Profile" page.
- When: The user clicks on "Edit My Profile."
- Then: The page should NOT log the user out.

**AC03: Ensure Editing User Details get saved**

- Given: The user is on the "My Profile" page.
- When: The user has made edits to their profile and clicked "Save."
- Then: The page should save the user's updates.

### Reviewer Notes:

During testing for AC02, this issue is not related to the editProfile component itself but is caused by the landingPage, specifically the "randomUser" login logic. The "randomUser" login button is not correctly authenticated, and as a result, user sessions do not persist across page refreshes when this button is used. It is recommended to create a separate ticket to tackle refactoring the logic surrounding the "randomUserLogin" function in the landing page, as this might require backend alterations or adding authentication logic in the landing page for it to work correctly. Alternatively, we can deprecate this function and discuss if we still need to use it in the next team meeting could be considered. Other than the issue related to AC02, the other acceptance criteria requirements are met. This issue could be related to the component behavior and might require further investigation or a separate ticket for resolution.

### Deployment Notes:

No special deployment requirements or changes are needed for this stability improvement.

This update ensures that users can edit their profiles without encountering crashes, and have their changes saved correctly. Further investigation is recommended for the additional issue noted during the review process.

_Please review and provide feedback as needed. Thank you!_

2023-09-17 03:55 UTC, yeezick commented on src/screens/UserProfile/EditProfile.tsx
> +// TODO: Added toast here as well
added is in past tense but i don't see it here

though toast logic is already implemented so it's already ready to use. [here's an example](https://github.com/yeezick/bootcampr/pull/85/files#diff-2b500cbe61fddf476289d130279517677d9f214e2b67220905a4577929762396R119-R126)

2023-09-17 03:55 UTC, yeezick commented on src/screens/UserProfile/EditProfile.tsx
> +    console.log('authUser:', authUser)
console log

2023-09-17 03:55 UTC, yeezick commented on src/screens/UserProfile/EditProfile.tsx
> +        console.log('Updating user form with authUser:', authUser)
anotha1

2023-09-17 03:57 UTC, yeezick commented on src/screens/UserProfile/EditProfile.tsx
> +  const [updateUserForm, setUpdateUserForm] = useState<UserInterface>(emptyUser)
not sure why we had to rename this var but preferable to add the "d" => "updatedUserForm" 

"updateUserForm" sounds like a boolean or toggle to me

2023-09-17 03:59 UTC, yeezick requested changes
looks good after these comments!

2023-09-18 20:11 UTC, HectorIlarraza commented on src/screens/UserProfile/EditProfile.tsx
> +// TODO: Added toast here as well
My fault i meant to write a "Add toast here as well" but since u showed me an example i decided to implement it now

2023-09-18 22:54 UTC, yeezick submitted a review, later dismissed

2023-09-27 23:21 UTC, yeezick approved these changes

2023-09-27 23:23 UTC, merged