Feature/bc 493 profile details and team members screens 2
yeezick/bootcampr pull request #92
Opened 2023-10-02 23:15 UTC by laurenhatchett

created a second branch to avoid resolving major merge issues on original branch.

2023-10-11 12:43 UTC, yeezick commented on src/screens/Project/ProjectDetails.scss
> +  // flex-direction: column;
delete dead code

2023-10-11 12:43 UTC, yeezick commented on src/screens/Project/ProjectDetails.scss
> +    // font-family: $vep-font-family;
dead code

2023-10-11 12:43 UTC, yeezick commented on src/screens/Project/ProjectDetails.scss
> +align-items: flex-start;
not properly indented

2023-10-11 12:43 UTC, yeezick commented on src/screens/Project/ProjectDetails.scss
> +h1 {
there should be a line break between css selectors

2023-10-11 12:45 UTC, yeezick commented on src/screens/Project/ProjectDetails.tsx
> +            <img src={ProjectDetailsBanner} alt='bee'></img>
img tags are self closing <img />

2023-10-11 12:45 UTC, yeezick commented on src/screens/Project/Team.scss
> +/*team screen */
not needed

2023-10-11 12:45 UTC, yeezick commented on src/screens/Project/Team.scss
> +.-page-container {
is there meant to be a dash before page?

2023-10-11 12:46 UTC, yeezick commented on src/screens/Project/Team.scss
> +    // font-family: $vep-font-family;
dead code

2023-10-11 12:46 UTC, yeezick commented on src/screens/Project/Team.scss
> +.role-container {
huge line break?

2023-10-11 12:47 UTC, yeezick commented on src/screens/Project/Team.tsx
> +//TODO: fix styling to match Figma
are these todo's still needed?

2023-10-11 12:47 UTC, yeezick commented on src/screens/Project/Team.tsx
> +  console.log(teamMembers)
console logs

2023-10-11 12:47 UTC, yeezick commented on src/screens/Project/Team.tsx
> +    <>
is this fragment needed?

2023-10-11 12:48 UTC, yeezick commented on src/screens/Project/Team.tsx
> +                      onClick={() => handleCloseModals()}
onClicks that dont need arguments can be used coded like:
`onClick={handleCloseModals}`

2023-10-11 12:48 UTC, yeezick commented on src/screens/Project/Team.tsx
> +          {showConfirmationModal && (
the modal itself should be its own component

2023-10-11 12:49 UTC, yeezick commented on src/screens/Project/Team.tsx
> +          {showConfirmationModal && (
we should be using MUI for modals

2023-10-11 12:49 UTC, yeezick commented on src/screens/Project/Team.tsx
> +const TeamMemberInfo = ({ teamMembers, loggedInUserId }) => {
need a line break between functions unless they are one-liners

2023-10-11 12:51 UTC, yeezick commented on src/screens/Project/Team.tsx
> +                />
Mapping over team members by role should be a reusable function instead of hardcoding the map per role

2023-10-11 12:51 UTC, yeezick commented on src/screens/Project/TeamMemberCard.scss
> +
white space

2023-10-11 12:51 UTC, yeezick commented on src/screens/Project/TeamMemberCard.scss
> +
whitespace

2023-10-11 12:52 UTC, yeezick commented on src/screens/Project/TeamMemberCard.scss
> +  label {  //TODO: what is happening here?
what's up with this todo?

2023-10-11 12:52 UTC, yeezick commented on src/screens/Project/TeamMemberCard.scss
> +padding: 0;
not indented properly

2023-10-11 12:52 UTC, yeezick commented on src/screens/Project/TeamMemberCard.scss
> +  p {
line break between selectors

2023-10-11 12:53 UTC, yeezick commented on src/screens/Project/TeamMemberCard.tsx
> +  const isCurrentUser = member._id === loggedInUserId
are these todo's still needed

2023-10-11 12:53 UTC, yeezick commented on src/screens/Project/TeamMemberCard.tsx
> +              )}
the current user should never be rendered in the team members page

2023-10-11 12:54 UTC, yeezick commented on src/screens/Project/TeamWithdrawal.tsx
> +              <button className='stay-btn' onClick={() => handleCloseModals()}>
`onClick={handleCloseModals}`

2023-10-11 12:54 UTC, yeezick commented on src/screens/UserProfile/UserProfile.tsx
> +      console.log(profileId?.id)
console log

2023-10-11 12:55 UTC, yeezick commented on src/screens/UserProfile/UserProfile.tsx
> +            {userProfileInfo?.firstName && userProfileInfo?.lastName && (
second conditional not needed, if the user has a first name they should have a last. required during sign up.

2023-10-11 12:55 UTC, yeezick commented on src/screens/UserProfile/UserProfile.tsx
> +            {(userProfileInfo?.role === 'Software Engineer' ||
role is required during sign up, these conditionals aren't needed

2023-10-11 12:56 UTC, yeezick commented on src/screens/UserProfile/UserProfile.tsx
> +          )}
role should not determine whether or not a user has a bio, the bio should determine that

2023-10-11 12:58 UTC, yeezick commented on src/screens/UserProfile/UserProfile.tsx
> +                )}
role should not determine if there are links, links should determine that

2023-10-11 12:59 UTC, yeezick commented on src/screens/UserProfile/UserProfile.tsx
> +                )}
the div that renders all links should be its own component

2023-10-11 13:00 UTC, yeezick requested changes
good alphabetization and code looks generally good. 
most comments are recurring instances of not adhering to best practices. 
other comments are about componentization.

2023-10-23 21:08 UTC, laurenhatchett commented on src/screens/Project/TeamMemberCard.tsx
> +              )}
In the last meeting (Oct 18th) didn't we agree to keep the current user's info to be in the Team Members Page? This is what shows on the Figma page. Can you confirm?

2023-10-23 23:27 UTC, yeezick commented on src/screens/Project/TeamMemberCard.tsx
> +              )}
We confirmed with UX last monday that yes they do want this. good catch

2023-12-10 07:57 UTC, HectorIlarraza commented
### Feature: Profile Details and Team Members Screen Implementation

This task involves the creation of two essential screens: the Profile Details page and the Team Members page. The Profile Details page provides information about the project, while the Team Members page showcases cards for all the team members. Additionally, the user can navigate to individual user profiles from the Team Members page.

### Changes Made:

1. Profile Details Page:

- Created and designed the Profile Details page to match the Figma design specifications.
- Implemented the layout and structure to showcase essential project details.

2. Profile Picture Editing Functionality:

- Created and designed the Team Members page as per the Figma design.
- Implemented the card view for displaying team members' information.

3. User Profile Navigation:

- Added logic to the Team Members page to handle clicks on the "Profile" button.
- Implemented functionality to fetch the user's stored information from the project slice.
- Integrated routing to the UserProfile component to display the selected user's information.

### Review Notes:

As I'll explain below, we will need to create several tickets after merging this one into dev.
- Withdrawal button logic and flow ticket
- Snackbar component for Withdrawal component ticket
- Create message button logic to navigate to team members private chat log (Big ticket) 

### Deployment Notes:

No specific deployment requirements for this feature. The changes will be included in the next deployment cycle.

**_Please review the changes and provide feedback as necessary. Thank you!_**

2023-12-18 23:05 UTC, yeezick commented on src/components/TeamAvatar/TeamAvatar.scss
> +.team_avatar {
CSS best practice is snake-case!

2023-12-18 23:06 UTC, yeezick commented on src/components/Timeline/TimelineList.tsx
> +import { timelineData } from '../../utils/data/timelineConstants'
should be able to import form utils without relative path

2023-12-18 23:12 UTC, yeezick requested changes
impressive CSS skills! minor comments to align with best practices

2023-12-18 23:13 UTC, yeezick commented on src/screens/UserProfile/UserProfile.tsx
>    // BC-334: should handle this case
Something I'd like to start doing is replacing TODOs with ticket IDs like shown here. This way when the ticket is picked up, they can easily perform a global search to identify where to implement logic

But this is new and I won't stop that from getting this code merged in!

2023-12-22 16:23 UTC, yeezick approved these changes

2023-12-22 16:23 UTC, merged